Repository nasa/openmct, pull requests merged in 2020-10, with the labels that each got.

#3269 Fixes for Testathon 08-03-20 issues
  src/plugins/tabs/components/tabs.scss
  src/plugins/tabs/components/tabs.vue
  src/plugins/telemetryTable/components/table.scss
  src/ui/components/object-label.scss
Labels: Target: 1.3.2

#3403 [Navigation Tree] Revert locked navigation and handle multiple requests
  src/ui/layout/mct-tree.vue
Labels: Target: 1.3.2

#3397 [Imagery Plugin] Data integration facilitation
  src/plugins/imagery/components/ImageryViewLayout.vue
Labels: Target: 1.3.2

#3308 Imagery Age to be displayed for realtime mode in Imagery View
  example/imagery/plugin.js
  src/plugins/imagery/components/ImageryViewLayout.vue
  src/plugins/imagery/components/imagery-view-layout.scss
  src/styles/_mixins.scss
Labels: Target: 1.3.2

#3385 Fix scroll issues in tree overflow state
  src/ui/layout/mct-tree.scss
  src/ui/layout/mct-tree.vue
  src/ui/layout/tree-item.vue
Labels: Target: 1.3.2

#3430 [Navigation Tree] Race condition on checking document readystate
  src/ui/layout/mct-tree.vue
  src/ui/layout/tree-item.vue
Labels: Target: 1.3.2, blocker

#3437 Cache gets
  src/api/objects/ObjectAPI.js
  src/api/objects/ObjectAPISpec.js
Labels: Target: 1.3.2

#3454 Duplicate tree ancestors fix
  src/ui/layout/mct-tree.vue
  src/ui/layout/tree-item.vue
Labels: unverified

#3313 [Plots] Toggle grid lines
  src/plugins/plot/res/templates/mct-plot.html
  src/plugins/plot/res/templates/plot.html
  src/plugins/plot/res/templates/stacked-plot.html
  src/plugins/plot/src/plot/MCTPlotController.js
  src/plugins/plot/src/telemetry/PlotController.js
  src/plugins/plot/src/telemetry/StackedPlotController.js
Labels: Improvement, R4.6

#3331 [Display Layout] User should be able to toggle grid lines
  src/plugins/displayLayout/DisplayLayoutToolbar.js
  src/plugins/displayLayout/components/DisplayLayout.vue
  src/plugins/displayLayout/components/DisplayLayoutGrid.vue
  src/plugins/displayLayout/plugin.js
  src/plugins/displayLayout/pluginSpec.js
  src/styles/_controls.scss
  src/ui/toolbar/Toolbar.vue
Labels: Improvement, R4.6

#3330 [Display Layout] Grid lines should show and hide appropriately for nested layouts
  src/plugins/displayLayout/components/display-layout.scss
Labels: bug

#3333 [Display Layout] User should be able to set outer dimensions
  src/plugins/displayLayout/DisplayLayoutType.js
  src/plugins/displayLayout/components/DisplayLayout.vue
  src/plugins/displayLayout/components/display-layout.scss
  src/styles/_constants-espresso.scss
  src/styles/_constants-maelstrom.scss
  src/styles/_constants-snow.scss
Labels: Improvement, R4.6
