Repository nasa/openmct, pull requests merged in 2020-04, with the labels that each got.

#2851 [Conditionals] Improve logic for Operation Format chooser
  src/plugins/condition/components/Criterion.vue
Labels: Target: VIPER

#2858 request LAD for default condition
  src/plugins/condition/ConditionManager.js
Labels: Target: VIPER

#2871 [Conditionals] Request and subscription results are mutually exclusive
  src/plugins/condition/Condition.js
  src/plugins/condition/ConditionManager.js
  src/plugins/condition/ConditionManagerSpec.js
  src/plugins/condition/ConditionSpec.js
  src/plugins/condition/utils/time.js
Labels: Target: VIPER

#2888 Notebook context menu
  src/plugins/notebook/components/menu-items.vue
  src/plugins/notebook/components/notebook-embed.vue
  src/plugins/notebook/components/notebook-snapshot-container.vue
  src/plugins/notebook/components/page-component.vue
  src/plugins/notebook/components/popup-menu.vue
  src/plugins/notebook/components/section-component.vue
  src/plugins/notebook/utils/popup-menu.js
  src/plugins/notebook/utils/removeDialog.js
Labels: Target:VISTA-R4.4, critical

#2907 Handles static and mixed styles for multiple items in a layout
  src/plugins/condition/StyleRuleManager.js
  src/plugins/condition/components/inspector/ConditionalStylesView.vue
  src/plugins/condition/components/inspector/MultiSelectStylesView.vue
  src/plugins/condition/components/inspector/StyleEditor.vue
  src/plugins/condition/utils/styleUtils.js
  src/plugins/displayLayout/components/BoxView.vue
  src/plugins/displayLayout/components/ImageView.vue
  src/plugins/displayLayout/components/LineView.vue
  src/plugins/displayLayout/components/TelemetryView.vue
  src/plugins/displayLayout/components/TextView.vue
  src/plugins/displayLayout/components/layout-frame.scss
  src/plugins/displayLayout/components/text-view.scss
  src/plugins/displayLayout/mixins/objectStyles-mixin.js
  src/styles/_controls.scss
  src/styles/_legacy.scss
  src/styles/_mixins.scss
  src/ui/components/ObjectView.vue
  src/ui/inspector/StylesInspectorView.vue
Labels: Target:VISTA-R4.4

#2864 [Notebook]: Entries filter #2820
  src/plugins/notebook/components/notebook.vue
Labels: Target:VISTA-R4.4

#2904 Ensures correct results are returned for conditions and criteria for a given telemetry datapoint
  src/plugins/condition/Condition.js
  src/plugins/condition/ConditionManager.js
  src/plugins/condition/ConditionManagerSpec.js
  src/plugins/condition/ConditionSpec.js
  src/plugins/condition/criterion/AllTelemetryCriterion.js
  src/plugins/condition/criterion/TelemetryCriterion.js
  src/plugins/condition/criterion/TelemetryCriterionSpec.js
  src/plugins/condition/utils/evaluator.js
  src/plugins/condition/utils/evaluatorSpec.js
  src/plugins/condition/utils/time.js
Labels: Target:VISTA-R4.4

#2914 [Conditionals] Only provide telemetry for incoming telemetry that is used
  src/plugins/condition/Condition.js
  src/plugins/condition/ConditionManager.js
Labels: Target: VIPER, critical

#2885 Lodash upgrade
  .eslintrc.js
  package.json
  platform/telemetry/src/TelemetryCapability.js
  src/api/composition/DefaultCompositionProvider.js
  src/api/telemetry/DefaultMetadataProvider.js
  src/api/telemetry/TelemetryAPI.js
  src/api/telemetry/TelemetryMetadataManager.js
  src/plugins/imagery/components/ImageryViewLayout.vue
  src/plugins/plot/src/chart/MCTChartController.js
  src/plugins/plot/src/telemetry/StackedPlotController.js
  src/plugins/summaryWidget/src/telemetry/SummaryWidgetEvaluator.js
  src/plugins/telemetryTable/TelemetryTableConfiguration.js
  src/plugins/telemetryTable/collections/SortedTableRowCollection.js
Labels: critical
