Repository nasa/openmct, pull requests merged in 2020-05, with the labels that each got.

#3011 Fixes marquee issue when user leaves window while mouse is still down
  src/plugins/plot/src/plot/MCTPlotController.js
Labels: Target:R4.4.1

#3013 Fixes plot end marquee and lock highlight issue
  src/plugins/plot/src/plot/MCTPlotController.js
Labels: Target:R4.5

#2958 Allow users to lazy load Tabs
  src/plugins/tabs/components/tabs.vue
  src/plugins/tabs/plugin.js
Labels: Target:R4.4.1, Target:R4.5

#3009 Tabs 4.4.1 Lazy Load
  src/plugins/tabs/components/tabs.vue
  src/plugins/tabs/plugin.js
Labels: Target:R4.4.1

#3010 Regex search 4.4.1
  src/plugins/telemetryTable/collections/FilteredTableRowCollection.js
  src/plugins/telemetryTable/components/table.vue
  src/ui/components/search.scss
  src/ui/components/search.vue
Labels: Target:R4.4.1

#3019 Bug fixes for plots
  src/plugins/plot/src/configuration/PlotSeries.js
  src/plugins/plot/src/configuration/YAxisModel.js
  src/plugins/plot/src/plot/MCTPlotController.js
Labels: Target:R4.4.1

#3015 [Time Conductor] add history and select range features to vista-r4.4.1
  index.html
  src/plugins/localTimeSystem/LocalTimeSystem.js
  src/plugins/timeConductor/Conductor.vue
  src/plugins/timeConductor/ConductorAxis.vue
  src/plugins/timeConductor/ConductorHistory.vue
  src/plugins/timeConductor/ConductorMode.vue
  src/plugins/timeConductor/conductor-axis.scss
  src/plugins/timeConductor/conductor.scss
  src/styles/_constants-espresso.scss
  src/styles/_constants-maelstrom.scss
  src/styles/_constants-snow.scss
  src/styles/_controls.scss
Labels: Target:R4.4.1

#3042 [Notebook] Clicking on an embed in a notebook entry does not result i…n bounds change #3034
  src/plugins/notebook/components/notebook-embed.vue
Labels: critical

#3036 [Plots] Prevent plots from requesting new data when a user clicks on the plot
  src/plugins/plot/src/plot/MCTPlotController.js
Labels: bug, critical
