Repository nasa/openmct, pull requests merged in 2021-05, with the labels that each got.

#2956 Regex search tables
  src/plugins/condition/components/inspector/StylesView.vue
  src/plugins/condition/utils/styleUtils.js
  src/plugins/telemetryTable/TelemetryTable.js
  src/plugins/telemetryTable/TelemetryTableViewProvider.js
  src/plugins/telemetryTable/collections/FilteredTableRowCollection.js
  src/plugins/telemetryTable/components/table.vue
  src/plugins/telemetryTable/pluginSpec.js
  src/ui/components/search.scss
  src/ui/components/search.vue
Labels: Target:R4.4.1, Target:R4.5

#3870 Pass objectPath as property to LAD rows
  src/plugins/LADTable/LADTableSetViewProvider.js
  src/plugins/LADTable/components/LADRow.vue
  src/plugins/LADTable/components/LADTable.vue
  src/plugins/LADTable/components/LadTableSet.vue
Labels: Target: 1.7.2

#3902 Updates to recognize issue template config
  .github/ISSUE_TEMPLATE/config.yml
  .github/PULL_REQUEST_TEMPLATE.md
Labels: chore
