Repository nasa/openmct, pull requests merged in 2021-02, with the labels that each got.

#3640 [Object API] remove unused code
  src/api/objects/objectEventEmitter.js
Labels: maintenance

#3659 [Feature Branch] Add Compass Rose and Compass HUD to Imagery View
  src/plugins/imagery/ImageryViewProvider.js
  src/plugins/imagery/components/Compass/Compass.vue
  src/plugins/imagery/components/Compass/CompassHUD.vue
  src/plugins/imagery/components/Compass/CompassRose.vue
  src/plugins/imagery/components/Compass/compass.scss
  src/plugins/imagery/components/Compass/utils.js
  src/plugins/imagery/components/ImageryViewLayout.vue
  src/plugins/imagery/components/imagery-view-layout.scss
  src/plugins/imagery/plugin.js
  src/styles/vue-styles.scss
Labels: Improvement

#3586 Plots refactor to use Vue and es6 instead of angular
  src/plugins/goToOriginalAction/pluginSpec.js
  src/plugins/interceptors/pluginSpec.js
  src/plugins/plot/vue/overlayPlot/OverlayPlotViewProvider.js
  src/plugins/plot/vue/single/LinearScale.js
  src/plugins/plot/vue/single/MctPlot.vue
  src/plugins/plot/vue/single/MctTicks.vue
  src/plugins/plot/vue/single/Plot.vue
  src/plugins/plot/vue/single/PlotViewProvider.js
  src/plugins/plot/vue/single/axis/XAxis.vue
  src/plugins/plot/vue/single/axis/YAxis.vue
  src/plugins/plot/vue/single/chart/MCTChartAlarmPointSet.js
  src/plugins/plot/vue/single/chart/MCTChartLineLinear.js
  src/plugins/plot/vue/single/chart/MCTChartLineStepAfter.js
  src/plugins/plot/vue/single/chart/MCTChartPointSet.js
  src/plugins/plot/vue/single/chart/MCTChartSeriesElement.js
  src/plugins/plot/vue/single/chart/MctChart.vue
  src/plugins/plot/vue/single/configuration/Collection.js
  src/plugins/plot/vue/single/configuration/LegendModel.js
  src/plugins/plot/vue/single/configuration/Model.js
  src/plugins/plot/vue/single/configuration/PlotConfigurationModel.js
  src/plugins/plot/vue/single/configuration/PlotSeries.js
  src/plugins/plot/vue/single/configuration/SeriesCollection.js
  src/plugins/plot/vue/single/configuration/XAxisModel.js
  src/plugins/plot/vue/single/configuration/YAxisModel.js
  src/plugins/plot/vue/single/configuration/configStore.js
  src/plugins/plot/vue/single/draw/Draw2D.js
  src/plugins/plot/vue/single/draw/DrawLoader.js
  src/plugins/plot/vue/single/draw/DrawWebGL.js
  src/plugins/plot/vue/single/draw/MarkerShapes.js
  src/plugins/plot/vue/single/legend/PlotLegend.vue
  src/plugins/plot/vue/single/legend/PlotLegendItemCollapsed.vue
  src/plugins/plot/vue/single/legend/PlotLegendItemExpanded.vue
  src/plugins/plot/vue/single/lib/Color.js
  src/plugins/plot/vue/single/lib/ColorHelper.js
  src/plugins/plot/vue/single/lib/ColorPalette.js
  src/plugins/plot/vue/single/lib/eventHelpers.js
  src/plugins/plot/vue/single/plugin.js
  src/plugins/plot/vue/single/pluginSpec.js
  src/plugins/plot/vue/single/tickUtils.js
  src/plugins/plot/vue/stackedPlot/StackedPlot.vue
  src/plugins/plot/vue/stackedPlot/StackedPlotItem.vue
  src/plugins/plot/vue/stackedPlot/StackedPlotViewProvider.js
  src/plugins/plugins.js
  src/plugins/timeline/activities.json
  src/styles/_legacy-plots.scss
  src/ui/layout/mct-tree.vue
  src/ui/router/ApplicationRouter.js
Labels: build-4

#3674 Couchdb object synchronization
  src/MCT.js
  src/api/composition/CompositionCollection.js
  src/api/objects/MutableDomainObject.js
  src/api/objects/ObjectAPI.js
  src/api/objects/ObjectAPISpec.js
  src/plugins/CouchDBSearchFolder/plugin.js
  src/plugins/CouchDBSearchFolder/pluginSpec.js
  src/plugins/notebook/utils/notebook-entriesSpec.js
  src/plugins/persistence/couch/CouchObjectProvider.js
  src/plugins/persistence/couch/plugin.js
  src/plugins/persistence/couch/pluginSpec.js
  src/plugins/plugins.js
  src/plugins/timeline/Plan.vue
  src/ui/router/Browse.js
Labels: build-4

#3693 Improvements to Compass Rose and HUD
  src/plugins/imagery/components/Compass/Compass.vue
  src/plugins/imagery/components/Compass/CompassHUD.vue
  src/plugins/imagery/components/Compass/CompassRose.vue
  src/plugins/imagery/components/Compass/utils.js
  src/plugins/imagery/components/ImageryViewLayout.vue
Labels: build-4

#3675 [Imagery Plugin] Enhancements - Compass, HUD, Freshness
  src/plugins/imagery/ImageryViewProvider.js
  src/plugins/imagery/components/Compass/Compass.vue
  src/plugins/imagery/components/Compass/CompassHUD.vue
  src/plugins/imagery/components/Compass/CompassRose.vue
  src/plugins/imagery/components/Compass/compass.scss
  src/plugins/imagery/components/Compass/pluginSpec.js
  src/plugins/imagery/components/Compass/utils.js
  src/plugins/imagery/components/ImageryViewLayout.vue
  src/plugins/imagery/components/RelatedTelemetry/RelatedTelemetry.js
  src/plugins/imagery/components/imagery-view-layout.scss
  src/plugins/imagery/plugin.js
  src/plugins/imagery/pluginSpec.js
  src/styles/vue-styles.scss
Labels: build-4

#3690 Fixes isMutable error when domainobject is undefined
  src/plugins/displayLayout/components/SubobjectView.vue
  src/plugins/displayLayout/components/TelemetryView.vue
Labels: build-4
