Repository nasa/openmct, pull requests merged in 2021-03, with the labels that each got.

#3716 [Abort Search] Ability to Cancel Search Requests
  platform/entanglement/src/services/LocatingObjectDecorator.js
  platform/search/src/services/SearchAggregator.js
  src/adapter/services/LegacyObjectAPIInterceptor.js
  src/api/objects/ObjectAPI.js
  src/plugins/persistence/couch/CouchObjectProvider.js
  src/ui/layout/mct-tree.vue
Labels: build-4

#3723 [Imagery Freshness] Update Telemetry for Imagery Freshness
  src/plugins/imagery/components/ImageryViewLayout.vue
  src/plugins/imagery/components/RelatedTelemetry/RelatedTelemetry.js
Labels: build-4

#3736 Pass object path when getting views during object creation
  src/adapter/actions/ActionDialogDecorator.js
Labels: blocker, build-4

#3419 Add lookahead padding to the plan time axis
  src/plugins/plan/Plan.vue
  src/plugins/timeline/Plan.vue
Labels: Target: 1.3.2
