Repository nasa/openmct, pull requests merged in 2022-01, with the labels that each got.

#4614 Move all support for the legacy API into a plugin
  index.html
  src/MCT.js
  src/MCTSpec.js
  src/api/composition/CompositionAPI.js
  src/api/composition/CompositionAPISpec.js
  src/api/composition/DefaultCompositionProvider.js
  src/plugins/LADTable/LADTableViewProvider.js
  src/plugins/charts/pluginSpec.js
  src/plugins/clock/pluginSpec.js
  src/plugins/condition/ConditionSetViewPolicy.js
  src/plugins/condition/plugin.js
  src/plugins/legacySupport/BundleRegistry.js
  src/plugins/legacySupport/BundleRegistrySpec.js
  src/plugins/legacySupport/installDefaultBundles.js
  src/plugins/legacySupport/legacyRegistry.js
  src/plugins/legacySupport/legacyRegistrySpec.js
  src/plugins/legacySupport/plugin.js
  src/plugins/notificationIndicator/pluginSpec.js
  src/plugins/plot/pluginSpec.js
  src/plugins/plugins.js
  src/plugins/timer/components/Timer.vue
  src/plugins/timer/pluginSpec.js
  src/utils/clock/Ticker.js
Labels: pr:e2e, Target:1.8.3, pr:visual

#4624 Fix main object view
  src/plugins/conditionWidget/components/condition-widget.scss
  src/ui/components/ObjectView.vue
  src/ui/layout/layout.scss
Labels: pr:visual

#4706 Update all playwright dependencies to 1.17.2
  .circleci/config.yml
  package.json
Labels: pr:e2e, pr:visual

#4717 [e2e] Update Playwright config to include MMOC and Ipad
  .github/workflows/e2e-pr.yml
  .github/workflows/e2e-visual.yml
  e2e/.percy.yml
  e2e/playwright-ci.config.js
  e2e/playwright-local.config.js
  package.json
Labels: pr:e2e

#4715 Script to update all copyright dates - Mct4532
  package.json
Labels: pr:visual

#4749 [e2e] Update playwright to 1.18.0
  .circleci/config.yml
  package.json
Labels: dependencies, pr:e2e, pr:visual

#4756 [CI] Dependabot and PR Cop have conflicts
  .github/dependabot.yml
Labels: dependencies, prcop:disable

#4538 [UserAPI] [UserIndicator Plugin] [ExampleUserProvider Plugin] New user api and related functionality
  example/exampleUser/ExampleUserProvider.js
  example/exampleUser/exampleUserCreator.js
  example/exampleUser/plugin.js
  example/exampleUser/pluginSpec.js
  index.html
  src/MCT.js
  src/api/api.js
  src/api/forms/components/FormProperties.vue
  src/api/user/User.js
  src/api/user/UserAPI.js
  src/api/user/UserAPISpec.js
  src/api/user/constants.js
  src/plugins/plugins.js
  src/plugins/userIndicator/components/UserIndicator.vue
  src/plugins/userIndicator/plugin.js
  src/plugins/userIndicator/pluginSpec.js
  src/styles/_controls.scss
Labels: pr:e2e, pr:visual

#4762 [CI]Update dependabot rules again
  .github/dependabot.yml
  .github/workflows/prcop-config.json
Labels: dependencies

#4799 [CI] Update github actions automation to work across forks
  .github/workflows/e2e-pr.yml
Labels: pr:e2e
