Repository nasa/openmct, pull requests merged in 2022-10, with the labels that each got.

#5836 Have webpack-dev-server write webpack assets to disk
  webpack.dev.js
Labels: type:maintenance

#5883 Remove two types from package and pin others
  package.json
Labels: type:maintenance

#5886 Centre and wrap Condition Widget label
  src/plugins/conditionWidget/components/condition-widget.scss
Labels: type:enhancement, source:community

#5827 User attribution
  e2e/appActions.js
  src/api/annotation/AnnotationAPISpec.js
  src/api/objects/ObjectAPI.js
  src/api/objects/ObjectAPISpec.js
  src/plugins/plan/pluginSpec.js
  src/plugins/remove/RemoveAction.js
  src/ui/inspector/InspectorDetailsSpec.js
  src/ui/inspector/details/Properties.vue
Labels: type:feature

#5916 Fix persistence timestamp
  src/api/objects/MutableDomainObject.js
  src/api/objects/ObjectAPI.js
  src/api/objects/ObjectAPISpec.js
  src/plugins/notebook/components/Notebook.vue
Labels: pr:e2e:couchdb

#5930 Add e2e tests to npm package
  .npmignore
Labels: type:maintenance
