Repository nasa/openmct, pull requests merged in 2022-11, with the labels that each got.

#5958 skip one mo
  .github/dependabot.yml
Labels: type:maintenance

#5913 [e2e][couchdb] Add test coverage for mct5616
  e2e/tests/functional/forms.e2e.spec.js
  src/api/forms/components/controls/SelectField.vue
  src/plugins/clock/plugin.js
Labels: pr:e2e:couchdb

#5909 Add 'View type' label to Display Layout toolbar
  src/plugins/displayLayout/DisplayLayoutToolbar.js
Labels: source:community
