Repository nasa/openmct, pull requests merged in 2022-06, with the labels that each got.

#5278 Add visual test for create menu and display layout icon
  e2e/tests/visual/default.visual.spec.js
Labels: pr:visual

#5196 Add units to Gauges
  src/plugins/gauge/GaugePlugin.js
  src/plugins/gauge/GaugePluginSpec.js
  src/plugins/gauge/components/Gauge.vue
  src/plugins/gauge/components/GaugeFormController.vue
  src/plugins/gauge/gauge.scss
Labels: type:bug, Target:2.0.5

#4968 Imagery layers
  e2e/test-data/PerformanceDisplayLayout.json
  e2e/tests/performance/imagery.perf.spec.js
  e2e/tests/plugins/imagery/exampleImagery.e2e.spec.js
  example/imagery/plugin.js
  src/api/overlays/components/OverlayComponent.vue
  src/plugins/displayLayout/components/LayoutFrame.vue
  src/plugins/displayLayout/components/layout-frame.scss
  src/plugins/imagery/components/FilterSettings.vue
  src/plugins/imagery/components/ImageControls.vue
  src/plugins/imagery/components/ImageryView.vue
  src/plugins/imagery/components/ImageryViewMenuSwitcher.vue
  src/plugins/imagery/components/LayerSettings.vue
  src/plugins/imagery/components/ZoomSettings.vue
  src/plugins/imagery/components/imagery-view.scss
  src/plugins/imagery/layers/example-imagery-layer-16x9.png
  src/plugins/imagery/layers/example-imagery-layer-safe.png
  src/plugins/imagery/layers/example-imagery-layer-scale.png
  src/plugins/imagery/pluginSpec.js
  src/plugins/telemetryTable/components/table.scss
  src/styles/_controls.scss
  src/styles/_global.scss
  src/styles/_legacy-plots.scss
  src/styles/_table.scss
  src/ui/components/ObjectFrame.vue
  src/ui/components/object-frame.scss
  webpack.common.js
Labels: pr:e2e, pr:visual

#5298 [Fault Management] Fix class case issue not showing icon
  src/plugins/faultManagement/FaultManagementListItem.vue
Labels: type:bug, unverified, dev:build-6, Target:2.0.5

#5192 Let Imagery be downloaded
  src/plugins/imagery/components/imagery-view.scss
Labels: Target:2.0.5

#5314 Fix wrong Grid view icon artwork
  src/styles/_constants.scss
  src/styles/_glyphs.scss
Labels: Target:2.0.6

#5369 Gauge fixes for Firefox and units display
  example/generator/plugin.js
  src/plugins/gauge/GaugePluginSpec.js
  src/plugins/gauge/components/Gauge.vue
  src/plugins/gauge/gauge.scss
Labels: pr:visual
