Repository nasa/openmct, pull requests merged in 2022-02, with the labels that each got.

#4805 [CI] Update playwright to 1.18.1
  .circleci/config.yml
  package.json
Labels: dependencies, pr:e2e, pr:visual, pr:daveit

#4795 [CI] Dependabot to run on all packages. Pin Packages. Remove unused packages
  .github/dependabot.yml
  app.js
  package.json
Labels: dependencies, pr:daveit

#4677 Separate out object name checking from the sorting function
  src/ui/layout/mct-tree.vue
Labels: pr:e2e

#4866 Bumped dependency versions to fix build issues in Node 16 and later
  package.json
  webpack.common.js
Labels: pr:e2e, pr:visual

#4868 [CI] Update CI to use node16 by default
  .circleci/config.yml
  .github/workflows/e2e-pr.yml
  .github/workflows/e2e-visual.yml
  .github/workflows/e2e.yml
  .github/workflows/lighthouse.yml
  .github/workflows/npm-prerelease.yml
Labels: pr:e2e, pr:visual

#4855 [CI] Update PR Cop to run on more events
  .github/workflows/e2e-pr.yml
  .github/workflows/e2e-visual.yml
  .github/workflows/prcop.yml
Labels: pr:e2e, pr:visual, pr:daveit

#4873 [CI] Update playwright to 1.19.1
  .circleci/config.yml
  package.json
Labels: dependencies, pr:e2e, pr:visual, pr:daveit

#4817 [CI] Enable Per PR Lighthouse CI Execution, Run nightly
  .github/workflows/lighthouse.yml
Labels: dependencies, pr:lighthouse

#4840 [CI] Add windows OS and Mac OS to CI testing
  .github/dependabot.yml
  .github/workflows/e2e-pr.yml
  .github/workflows/pr-platform.yml
Labels: pr:e2e

#4764 [Notebook] Add active user to entries
  src/plugins/notebook/components/Notebook.vue
  src/plugins/notebook/components/NotebookEntry.vue
  src/plugins/notebook/snapshot.js
  src/plugins/notebook/utils/notebook-entries.js
  src/plugins/notebook/utils/notebook-entriesSpec.js
Labels: pr:visual

#4891 Bugfix/issue 4684
  src/plugins/plugins.js
  src/plugins/staticRootPlugin/StaticModelProvider.js
  src/plugins/staticRootPlugin/StaticModelProviderSpec.js
  src/plugins/staticRootPlugin/plugin.js
Labels: pr:visual
