Repository nasa/openmct, pull requests merged in 2023-03, with the labels that each got.

#6306 fix(#5975): Transaction-ify the CreateAction
  e2e/tests/functional/search.e2e.spec.js
  e2e/tests/functional/tree.e2e.spec.js
  src/plugins/formActions/CreateAction.js
Labels: pr:e2e:couchdb

#6365 Fix Notebook enter key 6354
  e2e/helper/notebookUtils.js
  e2e/tests/functional/plugins/notebook/tags.e2e.spec.js
  src/plugins/notebook/components/Notebook.vue
  src/plugins/notebook/components/NotebookEntry.vue
  src/styles/notebook.scss
Labels: pr:e2e:couchdb

#6244 Conditional set output is wrong
  e2e/tests/functional/plugins/conditionSet/conditionSet.e2e.spec.js
  src/plugins/condition/ConditionManager.js
  src/plugins/condition/components/Condition.vue
  src/plugins/condition/components/ConditionCollection.vue
  src/plugins/condition/components/ConditionSet.vue
  src/plugins/condition/components/Criterion.vue
  src/plugins/displayLayout/components/AlphanumericFormat.vue
  src/plugins/displayLayout/components/TelemetryView.vue
Labels: sim-3

#6446 Clicking a plot annotation should pause the plot
  e2e/tests/functional/plugins/plot/tagging.e2e.spec.js
  src/plugins/plot/MctPlot.vue
  src/ui/layout/search/AnnotationSearchResult.vue
Labels: sim-3

#5876 Improvements to reduce repainting
  e2e/tests/functional/plugins/plot/autoscale.e2e.spec.js-snapshots/autoscale-canvas-panned-chrome-linux.png
  e2e/tests/functional/plugins/plot/autoscale.e2e.spec.js-snapshots/autoscale-canvas-prepan-chrome-linux.png
  e2e/tests/functional/plugins/plot/stackedPlot.e2e.spec.js
  e2e/tests/functional/search.e2e.spec.js
  e2e/tests/performance/notebook.perf.spec.js
  e2e/tests/visual/plan.visual.spec.js
  src/api/overlays/components/overlay-component.scss
  src/plugins/condition/components/inspector/conditional-styles.scss
  src/plugins/displayLayout/components/display-layout.scss
  src/plugins/displayLayout/components/layout-frame.scss
  src/plugins/flexibleLayout/components/flexible-layout.scss
  src/plugins/folderView/components/grid-view.scss
  src/plugins/imagery/components/imagery-view.scss
  src/plugins/inspectorViews/annotations/tags/tags.scss
  src/plugins/inspectorViews/properties/location.scss
  src/plugins/notebook/components/sidebar.scss
  src/plugins/timeConductor/conductor-axis.scss
  src/plugins/timeConductor/conductor.scss
  src/styles/_constants-espresso.scss
  src/styles/_constants-maelstrom.scss
  src/styles/_constants-mobile.scss
  src/styles/_constants-snow.scss
  src/styles/_constants.scss
  src/styles/_controls.scss
  src/styles/_legacy.scss
  src/styles/_mixins.scss
  src/ui/components/List/list-view.scss
  src/ui/components/object-frame.scss
  src/ui/components/object-label.scss
  src/ui/components/search.scss
  src/ui/inspector/inspector.scss
  src/ui/layout/create-button.scss
  src/ui/layout/layout.scss
  src/ui/layout/mct-tree.scss
  src/ui/layout/pane.scss
  src/ui/layout/status-bar/indicators.scss
Labels: sim-3

#6462 fix(#6455): fix Create modal tree infinite loop
  e2e/tests/functional/tree.e2e.spec.js
  src/ui/layout/mct-tree.vue
Labels: sim-3

#6464 fixes to entries
  src/plugins/notebook/components/Notebook.vue
  src/plugins/notebook/components/NotebookEntry.vue
Labels: sim-3

#6410 fix(#6408): Zooming in the corner of an image makes it fly away
  src/plugins/imagery/components/ImageryView.vue
Labels: source:community

#6327 Button to clear the recent objects list
  e2e/tests/functional/recentObjects.e2e.spec.js
  src/ui/layout/Layout.vue
  src/ui/layout/RecentObjectsList.vue
Labels: source:community

#6396 fix(#6347): Searching a Notebook with whitelisted links for '.' exposes some html
  src/utils/textHighlight/TextHighlight.vue
Labels: source:community

#6499 fix(#6457): Tags disappear after resizing then dismissing the Add Tag select
  src/plugins/inspectorViews/annotations/tags/TagEditor.vue
Labels: source:community

#6527 [Build]Remove Node14LTS from supported versions and update our pipelines
  .circleci/config.yml
  .github/workflows/pr-platform.yml
  package.json
Labels: pr:e2e, pr:platform, pr:e2e:couchdb

#6540 Github doesn't like node '16'
  .github/workflows/e2e-couchdb.yml
  package.json
Labels: pr:platform, pr:e2e:couchdb
