Repository nasa/openmct, pull requests merged in 2023-11, with the labels that each got.

#7173 docs: update Telemetry Formats section
  API.md
Labels: type:docs

#7201 chore: bump Playwright to v1.39.0
  .circleci/config.yml
  .github/workflows/e2e-couchdb.yml
  .github/workflows/e2e-pr.yml
  package.json
Labels: type:maintenance, pr:daveit

#7111 docs: add related repos section to README.md
  README.md
Labels: type:docs

#7203 docs: add warning about deploying devServer to prod environment
  API.md
Labels: type:docs

#7193 Add static limit values to LAD tables
  e2e/tests/functional/plugins/lad/lad.e2e.spec.js
  src/plugins/LADTable/components/LadRow.vue
  src/plugins/LADTable/components/LadTable.vue
  src/plugins/LADTable/components/LadTableConfiguration.vue
Labels: type:feature

#7216 [CI] Dependabot skip rebasing on every merge
  .github/dependabot.yml
Labels: dependencies, type:maintenance

#6999 fix(index.html): use defer and move script to head
  index.html
Labels: type:maintenance, source:community, pr:e2e:couchdb

#7149 Defer rendering for inactive tabs in open mct tabbed view
  .cspell.json
  e2e/tests/functional/plugins/tabs/tabs.e2e.spec.js
  e2e/tests/functional/plugins/telemetryTable/telemetryTable.e2e.spec.js
  e2e/tests/performance/tabs.e2e.spec.js
  src/api/nice/NicelyCalled.js
  src/plugins/LADTable/components/LadRow.vue
  src/plugins/displayLayout/components/TelemetryView.vue
  src/plugins/gauge/components/GaugeComponent.vue
  src/plugins/plot/chart/MctChart.vue
  src/plugins/tabs/components/TabsComponent.vue
  src/plugins/telemetryTable/components/TableComponent.vue
  src/plugins/telemetryTable/pluginSpec.js
Labels: performance, type:feature

#7238 chore: bump version to `3.1.1`
  package.json
Labels: type:maintenance

#7260 [Build] Update to Node 20 and remove 16 (EOL)
  .circleci/config.yml
  .github/workflows/pr-platform.yml
  package.json
Labels: dependencies, type:maintenance
