Repository nasa/openmct, pull requests merged in 2023-08, with the labels that each got.

#6891 [CI] Update docker login step to work across forks and non-nasa-users
  .github/workflows/e2e-couchdb.yml
Labels: type:maintenance

#6860 chore: move indexTest to kebab-case
  index-test.js
  karma.conf.js
Labels: source:community, pr:e2e:couchdb

#6892 Feat(tooling): add cspell
  .circleci/config.yml
  .cspell.json
  package.json
Labels: type:maintenance, source:community, pr:e2e:couchdb

#6941 fix(package.json): add author
  package.json
Labels: source:community, pr:e2e:couchdb

#6952 Progress Bar Display
  src/ui/components/progress-bar.scss
Labels: source:community, pr:e2e:couchdb

#6938 feat(tooling): adds nvm
  .nvmrc
  README.md
Labels: source:community, pr:e2e:couchdb

#6962 fix(html): minor fixes from validation
  index.html
Labels: source:community, pr:e2e:couchdb

#6971 chore(package.json): add fields
  package.json
Labels: source:community, pr:e2e:couchdb

#6960 Add strategy latest and timeContext to auto flow tabular and gauge views
  src/plugins/autoflow/AutoflowTabularRowController.js
  src/plugins/gauge/components/Gauge.vue
Labels: type:bug

#6970 chore(npm): dont generate lockfile
  .npmrc
Labels: source:community, pr:e2e:couchdb

#6997 fix(readme): note sections
  README.md
Labels: source:community, pr:e2e:couchdb

#6996 fix(readme): indent correctly
  README.md
Labels: source:community, pr:e2e:couchdb

#6986 fix(dialog): empty description
  e2e/tests/functional/plugins/operatorStatus/operatorStatus.e2e.spec.js
  src/plugins/userIndicator/components/UserIndicator.vue
Labels: source:community, pr:e2e:couchdb

#6953 ProgressBar null not undefined
  src/api/notifications/NotificationAPI.js
  src/api/overlays/OverlayAPI.js
  src/plugins/formActions/CreateAction.js
  src/plugins/notebook/components/Notebook.vue
  src/plugins/plot/Plot.vue
  src/plugins/telemetryTable/components/table.vue
  src/ui/components/ProgressBar.vue
  src/ui/layout/BrowseBar.vue
  src/ui/layout/search/SearchResultsDropDown.vue
  src/ui/layout/status-bar/NotificationBanner.vue
Labels: source:community, pr:e2e:couchdb

#6969 feat(linting): concurrent linting
  .circleci/config.yml
  .github/workflows/pr-platform.yml
  package.json
Labels: source:community, pr:e2e:couchdb
