Repository nasa/openmct, pull requests merged in 2023-09, with the labels that each got.

#7044 cherry-pick(#5585): Light refactor of visual tests
  .circleci/config.yml
  .cspell.json
  e2e/.percy.ci.yml
  e2e/.percy.nightly.yml
  e2e/.percy.yml
  e2e/README.md
  e2e/appActions.js
  e2e/baseFixtures.js
  e2e/constants.js
  e2e/helper/notebookUtils.js
  e2e/pluginFixtures.js
  e2e/test-data/VisualTestData_storage.json
  e2e/test-data/overlay_plot_storage.json
  e2e/test-data/overlay_plot_with_delay_storage.json
  e2e/tests/framework/exampleTemplate.e2e.spec.js
  e2e/tests/framework/generateLocalStorageData.e2e.spec.js
  e2e/tests/framework/generateVisualTestData.e2e.spec.js
  e2e/tests/functional/plugins/notebook/restrictedNotebook.e2e.spec.js
  e2e/tests/functional/plugins/notebook/tags.e2e.spec.js
  e2e/tests/visual/addInit.visual.spec.js
  e2e/tests/visual/components/about.visual.spec.js
  e2e/tests/visual/components/tree.visual.spec.js
  e2e/tests/visual/controlledClock.visual.spec.js
  e2e/tests/visual/default.visual.spec.js
  e2e/tests/visual/defaultPlugins.visual.spec.js
  e2e/tests/visual/faultManagement.visual.spec.js
  e2e/tests/visual/notebook.visual.spec.js
  e2e/tests/visual/notification.visual.spec.js
  e2e/tests/visual/search.visual.spec.js
  package.json
  src/plugins/plot/inspector/PlotOptionsItem.vue
Labels: pr:e2e:couchdb

#6955 PascalCase files
  .eslintrc.js
  package.json
  src/api/forms/components/controls/Locator.vue
  src/plugins/LADTable/LADTableConfigurationViewProvider.js
  src/plugins/LADTable/LADTableView.js
  src/plugins/LADTable/components/LadRow.vue
  src/plugins/LADTable/components/LadTable.vue
  src/plugins/LADTable/components/LadTableConfiguration.vue
  src/plugins/LADTable/components/LadTableSet.vue
  src/plugins/clearData/components/GlobalClearIndicator.vue
  src/plugins/clearData/plugin.js
  src/plugins/condition/components/inspector/StyleEditor.vue
  src/plugins/faultManagement/FaultManagementSearch.vue
  src/plugins/flexibleLayout/components/Container.vue
  src/plugins/flexibleLayout/components/DropHint.vue
  src/plugins/flexibleLayout/components/FlexibleLayout.vue
  src/plugins/flexibleLayout/components/Frame.vue
  src/plugins/flexibleLayout/components/ResizeHandle.vue
  src/plugins/flexibleLayout/flexibleLayoutViewProvider.js
  src/plugins/imagery/components/Compass/Compass.vue
  src/plugins/imagery/components/Compass/CompassHud.vue
  src/plugins/inspectorViews/elements/ElementsPool.vue
  src/plugins/inspectorViews/elements/PlotElementsPool.vue
  src/plugins/inspectorViews/styles/StylesInspectorView.vue
  src/plugins/notebook/components/Notebook.vue
  src/plugins/tabs/components/Tabs.vue
  src/plugins/tabs/tabs.js
  src/plugins/telemetryTable/TableConfigurationViewProvider.js
  src/plugins/telemetryTable/TelemetryTableView.js
  src/plugins/telemetryTable/components/SizingRow.vue
  src/plugins/telemetryTable/components/Table.vue
  src/plugins/telemetryTable/components/TableCell.vue
  src/plugins/telemetryTable/components/TableColumnHeader.vue
  src/plugins/telemetryTable/components/TableConfiguration.vue
  src/plugins/telemetryTable/components/TableFooterIndicator.vue
  src/plugins/telemetryTable/components/TableRow.vue
  src/plugins/timeConductor/ConductorInputsFixed.vue
  src/plugins/timeConductor/ConductorInputsRealtime.vue
  src/plugins/timeConductor/TimePopupFixed.vue
  src/plugins/timeConductor/TimePopupRealtime.vue
  src/ui/components/ContextMenuDropDown.vue
  src/ui/components/Search.vue
  src/ui/components/ViewControl.vue
  src/ui/layout/Layout.vue
  src/ui/layout/MctTree.vue
  src/ui/layout/Multipane.vue
  src/ui/layout/Pane.vue
  src/ui/layout/TreeItem.vue
  src/ui/layout/search/GrandSearch.vue
  src/ui/preview/Preview.vue
  src/ui/preview/PreviewHeader.vue
  src/ui/toolbar/Toolbar.vue
  src/ui/toolbar/components/ToolbarButton.vue
  src/ui/toolbar/components/ToolbarCheckbox.vue
  src/ui/toolbar/components/ToolbarColorPicker.vue
  src/ui/toolbar/components/ToolbarInput.vue
  src/ui/toolbar/components/ToolbarMenu.vue
  src/ui/toolbar/components/ToolbarSelectMenu.vue
  src/ui/toolbar/components/ToolbarSeparator.vue
  src/ui/toolbar/components/ToolbarToggleButton.vue
Labels: source:community, pr:e2e:couchdb

#7073 Fix mojibake
  .webpack/webpack.common.js
Labels: bug:regression

#7000 fix(templates): move to own folder
  .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
Labels: source:community, pr:e2e:couchdb
