Repository nasa/openmct, pull requests merged in 2023-01, with the labels that each got.

#6076 [CLA on File]: tooling: improve bundler structure
  .webpack/webpack.common.js
  .webpack/webpack.coverage.js
  .webpack/webpack.dev.js
  .webpack/webpack.prod.js
  karma.conf.js
  package.json
  webpack.common.js
Labels: source:community

#6079 [CLA Approved] Remove notification independently
  e2e/appActions.js
  e2e/tests/framework/appActions.e2e.spec.js
  e2e/tests/functional/notification.e2e.spec.js
  e2e/tests/visual/notification.visual.spec.js
  package.json
  src/api/notifications/NotificationAPI.js
  src/api/overlays/components/OverlayComponent.vue
  src/plugins/notificationIndicator/components/NotificationIndicator.vue
  src/plugins/notificationIndicator/components/NotificationMessage.vue
  src/plugins/notificationIndicator/components/NotificationsList.vue
  src/ui/layout/status-bar/NotificationBanner.vue
Labels: source:community

#6123 tooling(webpack): base paths of rootfolder
  .webpack/webpack.common.js
  .webpack/webpack.dev.js
  .webpack/webpack.prod.js
Labels: source:community

#6133 Fix Notifications Overlay that opens automatically
  e2e/tests/functional/notification.e2e.spec.js
  src/plugins/notificationIndicator/components/NotificationIndicator.vue
Labels: source:community

#6036 [CLA on File] style: added padding to object & icon button labels
  e2e/tests/functional/plugins/plot/autoscale.e2e.spec.js-snapshots/autoscale-canvas-panned-chrome-darwin.png
  e2e/tests/functional/plugins/plot/autoscale.e2e.spec.js-snapshots/autoscale-canvas-panned-chrome-linux.png
  e2e/tests/functional/plugins/plot/autoscale.e2e.spec.js-snapshots/autoscale-canvas-prepan-chrome-darwin.png
  e2e/tests/functional/plugins/plot/autoscale.e2e.spec.js-snapshots/autoscale-canvas-prepan-chrome-linux.png
  src/styles/_controls.scss
  src/ui/components/object-label.scss
Labels: source:community

#5809 [Notebook] Embed enhancements
  e2e/tests/functional/plugins/notebook/notebook.e2e.spec.js
  e2e/tests/functional/plugins/notebook/notebookSnapshots.e2e.spec.js
  e2e/tests/functional/plugins/notebook/restrictedNotebook.e2e.spec.js
  src/plugins/notebook/components/NotebookEmbed.vue
  src/plugins/notebook/components/NotebookEntry.vue
  src/styles/_constants-espresso.scss
  src/styles/_constants-maelstrom.scss
  src/styles/_constants-snow.scss
  src/styles/_constants.scss
  src/styles/_controls.scss
  src/styles/_glyphs.scss
  src/styles/notebook.scss
  src/ui/components/tags/TagEditor.vue
  src/ui/components/tags/tags.scss
Labels: type:feature

#6090 [Notebook] Convert full links in entries, into clickable links
  e2e/tests/functional/plugins/notebook/notebook.e2e.spec.js
  e2e/tests/functional/plugins/notebook/notebookWithCouchDB.e2e.spec.js
  package.json
  src/plugins/notebook/NotebookViewProvider.js
  src/plugins/notebook/components/NotebookEntry.vue
  src/plugins/notebook/plugin.js
Labels: pr:e2e, pr:platform, pr:e2e:couchdb
