Repository nasa/openmct, pull requests merged in 2023-12, with the labels that each got.

#7253 chore(package.json): fix warning during npm publish
  package.json
Labels: type:maintenance

#7265 When searching, build the path objects asynchronously while returning the results
  src/api/annotation/AnnotationAPI.js
  src/api/objects/ObjectAPI.js
  src/ui/components/ObjectPath.vue
  src/ui/layout/search/GrandSearch.vue
  src/ui/layout/search/GrandSearchSpec.js
Labels: performance

#7236 [CLA Received] wrote an e2e test for can create a notebook object
  e2e/tests/functional/plugins/notebook/notebook.e2e.spec.js
Labels: type:maintenance, source:community, pr:e2e:couchdb

#7285 Update API Readme to indicate `renderWhenVisible` function is optional
  API.md
Labels: type:docs

#7298 fix: define main entry point in `package.json`
  package.json
Labels: type:maintenance

#7106 Fix Notebook entry hover problem
  e2e/tests/visual/notebook.visual.spec.js
  src/styles/_constants-espresso.scss
  src/styles/_constants-maelstrom.scss
  src/styles/_constants-snow.scss
  src/styles/notebook.scss
Labels: type:bug

#6803 Add CodeQL badge to readme
  README.md
Labels: type:maintenance

#5815 PR Cop 2.0
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/prcop.yml
Labels: type:maintenance

#7278 Defer intersection monitoring until needed to prevent race conditions
  API.md
  src/plugins/plot/chart/MctChart.vue
  src/utils/visibility/VisibilityObserver.js
Labels: type:bug, performance

#7300 Automatically check additional views for memory leaks on navigation
  e2e/test-data/memory-leak-detection.json
  e2e/tests/performance/memory/navigation.memory.perf.spec.js
  src/plugins/charts/bar/BarGraphPlot.vue
  src/plugins/charts/bar/inspector/BarGraphOptions.vue
  src/plugins/charts/bar/pluginSpec.js
  src/plugins/charts/scatter/ScatterPlotWithUnderlay.vue
Labels: type:maintenance, pr:e2e:quickstart

#7310 [CI] Remove unneeded parameterization and increase parallelism
  .circleci/config.yml
Labels: type:maintenance

#7047 [CI] Add a11y checks to our visual testing suite
  .circleci/config.yml
  .cspell.json
  e2e/.percy.ci.yml
  e2e/.percy.nightly.yml
  e2e/README.md
  e2e/avpFixtures.js
  e2e/helper/plotTagsUtils.js
  e2e/playwright-ci.config.js
  e2e/playwright-visual-a11y.config.js
  e2e/tests/functional/plugins/plot/tagging.e2e.spec.js
  e2e/tests/performance/tagging.perf.spec.js
  e2e/tests/visual-a11y/a11y.visual.spec.js
  e2e/tests/visual-a11y/components/about.visual.spec.js
  e2e/tests/visual-a11y/components/inspector.visual.spec.js
  e2e/tests/visual-a11y/components/tree.visual.spec.js
  e2e/tests/visual-a11y/controlledClock.visual.spec.js
  e2e/tests/visual-a11y/defaultPlugins.visual.spec.js
  e2e/tests/visual-a11y/displayLayout.visual.spec.js
  e2e/tests/visual-a11y/faultManagement.visual.spec.js
  e2e/tests/visual-a11y/ladTable.visual.spec.js
  e2e/tests/visual-a11y/notebook.visual.spec.js
  e2e/tests/visual-a11y/notification.visual.spec.js
  e2e/tests/visual-a11y/planning.visual.spec.js
  e2e/tests/visual-a11y/search.visual.spec.js
  index.html
  package.json
  src/plugins/clock/components/ClockIndicator.vue
  src/plugins/notebook/components/NotebookSnapshotIndicator.vue
  src/ui/components/SearchComponent.vue
  src/ui/layout/AppLayout.vue
  src/ui/layout/search/GrandSearch.vue
Labels: type:maintenance

#7246 Reduce bundle size
  .webpack/webpack.common.js
  e2e/tests/functional/plugins/notebook/notebookSnapshots.e2e.spec.js
  package.json
  src/api/telemetry/TelemetryValueFormatter.js
  src/plugins/displayLayout/CustomStringFormatter.js
  src/plugins/timeConductor/ConductorAxis.vue
  src/ui/components/TimeSystemAxis.vue
Labels: type:maintenance

#7326 chore: watch mode improvements
  e2e/README.md
  e2e/playwright-watch.config.js
  package.json
Labels: type:maintenance

#7328 fix: cleanup from #7029
  src/api/objects/object-utils.js
  src/plugins/autoflow/AutoflowTabularPlugin.js
  src/plugins/conditionWidget/components/ConditionWidget.vue
  src/plugins/hyperlink/HyperlinkLayout.vue
  src/plugins/timer/components/TimerComponent.vue
  src/plugins/webPage/components/WebPage.vue
  src/ui/router/ApplicationRouter.js
Labels: type:maintenance, pr:e2e:couchdb
