Repository nasa/openmct, pull requests merged in 2024-01, with the labels that each got.

#7319 [Flexible Layouts] Flexible Layout styling fixes
  .cspell.json
  .git-blame-ignore-revs
  e2e/.percy.ci.yml
  e2e/.percy.nightly.yml
  e2e/helper/stylingUtils.js
  e2e/tests/framework/exampleTemplate.e2e.spec.js
  e2e/tests/framework/generateLocalStorageData.e2e.spec.js
  e2e/tests/functional/clearDataAction.e2e.spec.js
  e2e/tests/functional/forms.e2e.spec.js
  e2e/tests/functional/plugins/conditionSet/conditionSet.e2e.spec.js
  e2e/tests/functional/plugins/flexibleLayout/flexibleLayout.e2e.spec.js
  e2e/tests/functional/plugins/gauge/gauge.e2e.spec.js
  e2e/tests/functional/plugins/notebook/notebook.e2e.spec.js
  e2e/tests/functional/plugins/notebook/notebookSnapshots.e2e.spec.js
  e2e/tests/functional/plugins/notebook/restrictedNotebook.e2e.spec.js
  e2e/tests/functional/plugins/notebook/tags.e2e.spec.js
  e2e/tests/functional/plugins/plot/plotRendering.e2e.spec.js
  e2e/tests/functional/plugins/styling/conditionalStyling.e2e.spec.js
  e2e/tests/functional/plugins/styling/flexLayoutStyling.e2e.spec.js
  e2e/tests/functional/plugins/styling/stackedPlotStyling.e2e.spec.js
  e2e/tests/functional/plugins/styling/styleInspectorOptions.e2e.spec.js
  e2e/tests/functional/plugins/timer/timer.e2e.spec.js
  e2e/tests/visual-a11y/ladTable.visual.spec.js
  e2e/tests/visual-a11y/styling.visual.spec.js
  src/api/menu/components/MenuComponent.vue
  src/api/menu/components/SuperMenu.vue
  src/plugins/flexibleLayout/components/ContainerComponent.vue
  src/plugins/flexibleLayout/components/FlexibleLayout.vue
  src/plugins/inspectorDataVisualization/TelemetryFrame.vue
  src/plugins/inspectorViews/styles/FontStyleEditor.vue
  src/plugins/inspectorViews/styles/StylesInspectorViewProvider.js
  src/plugins/notebook/components/NotebookEmbed.vue
  src/plugins/plot/stackedPlot/StackedPlot.vue
  src/ui/components/ObjectView.vue
  src/ui/layout/BrowseBar.vue
  src/ui/preview/PreviewHeader.vue
  src/ui/toolbar/ToolbarContainer.vue
  src/ui/toolbar/components/ToolbarButton.vue
  src/ui/toolbar/components/ToolbarColorPicker.vue
  src/ui/toolbar/components/ToolbarSeparator.vue
Labels: type:feature

#7341 fix(#7338): Persisted styles correctly apply to `StackedPlotItem`s on mount
  e2e/tests/functional/plugins/styling/stackedPlotStyling.e2e.spec.js
  src/plugins/plot/PlotView.vue
  src/plugins/plot/stackedPlot/StackedPlotItem.vue
  src/plugins/plot/stackedPlot/pluginSpec.js
Labels: type:bug

#7306 Set location hash if query parameters or path have changed
  e2e/tests/functional/notification.e2e.spec.js
  e2e/tests/functional/plugins/flexibleLayout/flexibleLayout.e2e.spec.js
  e2e/tests/functional/plugins/notebook/notebookWithCouchDB.e2e.spec.js
  e2e/tests/functional/plugins/notebook/tags.e2e.spec.js
  e2e/tests/functional/search.e2e.spec.js
  e2e/tests/visual-a11y/notification.visual.spec.js
  src/MCT.js
  src/api/overlays/components/OverlayComponent.vue
  src/plugins/clock/components/ClockComponent.vue
  src/ui/layout/search/AnnotationSearchResult.vue
  src/ui/layout/search/GrandSearchSpec.js
  src/ui/layout/search/ObjectSearchResult.vue
  src/ui/layout/search/SearchResultsDropDown.vue
  src/ui/preview/PreviewContainer.vue
  src/ui/router/ApplicationRouter.js
  src/ui/router/Browse.js
Labels: type:bug

#7194 Timelist centering algorithm change and duration formatting change
  e2e/constants.js
  e2e/helper/planningUtils.js
  e2e/test-data/examplePlans/ExamplePlan_Small3.json
  e2e/tests/functional/planning/timelist.e2e.spec.js
  src/plugins/timelist/TimelistComponent.vue
  src/utils/duration.js
Labels: type:enhancement

#7308 fix(#7055): Expand on image with double click
  e2e/tests/functional/plugins/imagery/exampleImagery.e2e.spec.js
  src/plugins/imagery/components/ImageryView.vue
Labels: type:bug, source:community, pr:e2e:couchdb

#7345 Clear active role if no longer in available roles
  e2e/tests/functional/userRoles.e2e.spec.js
  src/api/user/UserAPI.js
  src/plugins/userIndicator/components/UserIndicator.vue
Labels: type:bug

#7374 feat(#7367): ProgressBar for `ExportAsJSONAction`
  .webpack/webpack.common.js
  e2e/tests/functional/clearDataAction.e2e.spec.js
  e2e/tests/functional/plugins/plot/logPlot.e2e.spec.js
  example/imagery/plugin.js
  src/api/menu/MenuAPI.js
  src/api/overlays/Overlay.js
  src/api/overlays/OverlayAPI.js
  src/api/overlays/ProgressDialog.js
  src/api/overlays/components/ProgressDialogComponent.vue
  src/exporters/CSVExporter.js
  src/exporters/ImageExporter.js
  src/exporters/JSONExporter.js
  src/plugins/exportAsJSONAction/ExportAsJSONAction.js
  src/plugins/exportAsJSONAction/ExportAsJSONActionSpec.js
  src/plugins/localStorage/LocalStorageObjectProvider.js
  src/plugins/notebook/actions/ExportNotebookAsTextAction.js
  src/ui/components/ProgressBar.vue
  src/ui/inspector/InspectorStylesSpec.js
  src/utils/testing/mockLocalStorage.js
Labels: type:enhancement

#7384 Provide `renderWhenVisible` to LadTableSets
  e2e/tests/functional/plugins/inspectorDataVisualization/numericData.e2e.spec.js
  e2e/tests/functional/plugins/lad/lad.e2e.spec.js
  e2e/tests/functional/plugins/lad/ladSet.e2e.spec.js
  src/plugins/LADTable/LadTableSetView.js
  src/plugins/LADTable/components/LadRow.vue
  src/plugins/LADTable/components/LadTableConfiguration.vue
  src/plugins/LADTable/pluginSpec.js
  src/plugins/inspectorDataVisualization/TelemetryFrame.vue
Labels: type:bug

#7387 Mct7367-tests
  e2e/appActions.js
  e2e/helper/notebookUtils.js
  e2e/tests/framework/appActions.e2e.spec.js
  e2e/tests/functional/plugins/importAndExportAsJSON/exportAsJson.e2e.spec.js
  e2e/tests/functional/plugins/inspectorDataVisualization/numericData.e2e.spec.js
  e2e/tests/functional/plugins/lad/ladSet.e2e.spec.js
  e2e/tests/functional/plugins/notebook/notebookSnapshotImage.e2e.spec.js
  e2e/tests/functional/plugins/notebook/notebookSnapshots.e2e.spec.js
  e2e/tests/functional/plugins/notebook/notebookTags.e2e.spec.js
  e2e/tests/functional/plugins/operatorStatus/operatorStatus.e2e.spec.js
  e2e/tests/functional/userRoles.e2e.spec.js
  e2e/tests/visual-a11y/components/header.visual.spec.js
  src/plugins/imagery/components/ImageryView.vue
  src/ui/components/ProgressBar.vue
  src/ui/layout/AppLayout.vue
Labels: type:maintenance

#7395 feat(#7394): Incorporate Status Indicators into the main Vue app
  e2e/tests/functional/plugins/plot/overlayPlot.e2e.spec.js
  e2e/tests/functional/plugins/tabs/tabs.e2e.spec.js
  e2e/tests/functional/search.e2e.spec.js
  e2e/tests/visual-a11y/components/header.visual.spec.js
  e2e/tests/visual-a11y/faultManagement.visual.spec.js
  src/api/indicators/IndicatorAPI.js
  src/api/indicators/IndicatorAPISpec.js
  src/plugins/clearData/components/GlobalClearIndicator.vue
  src/plugins/clearData/plugin.js
  src/plugins/clearData/pluginSpec.js
  src/plugins/clock/components/ClockIndicator.vue
  src/plugins/clock/plugin.js
  src/plugins/clock/pluginSpec.js
  src/plugins/flexibleLayout/pluginSpec.js
  src/plugins/notebook/components/NotebookSnapshotIndicator.vue
  src/plugins/notebook/plugin.js
  src/plugins/notebook/pluginSpec.js
  src/plugins/notificationIndicator/components/NotificationIndicator.vue
  src/plugins/notificationIndicator/plugin.js
  src/ui/layout/AppLayout.vue
  src/ui/layout/status-bar/StatusIndicators.vue
  src/utils/vueWrapHtmlElement.js
Labels: type:enhancement, performance

#7409 Change Imagery positional freshness label from 'POS' to 'ROV'
  src/plugins/imagery/components/ImageryView.vue
Labels: type:enhancement, severity:critical

#7412 move performance tests to GHA
  .circleci/config.yml
  .github/workflows/e2e-perf.yml
  e2e/tests/functional/plugins/plot/overlayPlot.e2e.spec.js
  e2e/tests/visual-a11y/imagery.visual.spec.js
Labels: type:maintenance

#7362 New action to reload an individual view and all of its children
  e2e/tests/functional/plugins/reloadAction/reloadAction.e2e.spec.js
  e2e/tests/functional/plugins/tabs/tabs.e2e.spec.js
  e2e/tests/functional/plugins/telemetryTable/telemetryTable.e2e.spec.js
  e2e/tests/performance/tabs.e2e.spec.js
  src/MCT.js
  src/plugins/plugins.js
  src/plugins/reloadAction/ReloadAction.js
  src/plugins/reloadAction/plugin.js
  src/plugins/telemetryTable/components/TableCell.vue
  src/plugins/telemetryTable/components/TableComponent.vue
  src/ui/components/ObjectView.vue
Labels: type:feature, pr:e2e:perf

#7414 Fix actions menu on display layout alphanumerics
  e2e/tests/functional/plugins/displayLayout/displayLayout.e2e.spec.js
  src/plugins/displayLayout/components/TelemetryView.vue
Labels: type:bug

#7385 Get actions collection on Preview Container update
  e2e/tests/functional/plugins/preview/preview.e2e.spec.js
  src/ui/preview/PreviewContainer.vue
Labels: type:bug

#7392 Table CPU Performance Improvements
  src/plugins/telemetryTable/components/TableComponent.vue
Labels: type:enhancement, performance

#7399 Table performance paging
  .cspell.json
  e2e/README.md
  e2e/tests/functional/plugins/plot/autoscale.e2e.spec.js-snapshots/autoscale-canvas-panned-chrome-linux.png
  e2e/tests/functional/plugins/plot/autoscale.e2e.spec.js-snapshots/autoscale-canvas-prepan-chrome-linux.png
  example/generator/GeneratorProvider.js
  example/generator/generatorWorker.js
  package.json
  src/api/telemetry/TelemetryCollection.js
  src/plugins/telemetryTable/TelemetryTable.js
  src/plugins/telemetryTable/TelemetryTableConfiguration.js
  src/plugins/telemetryTable/TelemetryTableType.js
  src/plugins/telemetryTable/TelemetryTableView.js
  src/plugins/telemetryTable/TelemetryTableViewProvider.js
  src/plugins/telemetryTable/collections/TableRowCollection.js
  src/plugins/telemetryTable/components/TableComponent.vue
  src/plugins/telemetryTable/components/TableFooterIndicator.vue
  src/plugins/telemetryTable/components/table-footer-indicator.scss
  src/plugins/telemetryTable/components/table.scss
  src/plugins/telemetryTable/plugin.js
Labels: type:feature, notable_change

#7342 Set disabled items to use disabled property
  src/api/menu/components/MenuComponent.vue
  src/api/menu/components/SuperMenu.vue
  src/plugins/notebook/components/NotebookComponent.vue
  src/styles/_global.scss
  src/ui/layout/CreateButton.vue
  src/ui/layout/create-button.scss
  src/ui/layout/mct-tree.scss
Labels: type:bug

#7388 Add filtering by metadata
  src/plugins/plan/util.js
  src/plugins/timelist/TimelistComponent.vue
  src/plugins/timelist/inspector/FilteringComponent.vue
  src/plugins/timelist/plugin.js
  src/plugins/timelist/pluginSpec.js
Labels: type:feature, pr:e2e:perf

#7370 Activity state display for plans in Gantt and Time list views
  e2e/test-data/examplePlans/ExamplePlan_Small1.json
  e2e/test-data/examplePlans/ExamplePlan_Small3.json
  e2e/tests/functional/planning/plan.e2e.spec.js
  e2e/tests/functional/planning/timelist.e2e.spec.js
  src/api/objects/ObjectAPI.js
  src/plugins/activityStates/activityStatesInterceptor.js
  src/plugins/activityStates/createActivityStatesIdentifier.js
  src/plugins/activityStates/pluginSpec.js
  src/plugins/plan/components/ActivityTimeline.vue
  src/plugins/plan/components/PlanView.vue
  src/plugins/plan/inspector/components/PlanActivitiesView.vue
  src/plugins/plan/inspector/components/PlanActivityPropertiesView.vue
  src/plugins/plan/inspector/components/PlanActivityStatusView.vue
  src/plugins/plan/inspector/components/PlanActivityTimeView.vue
  src/plugins/plan/plugin.js
  src/plugins/plan/util.js
  src/plugins/telemetryTable/components/table.scss
  src/plugins/timelist/TimelistComponent.vue
  src/plugins/timelist/inspector/TimeListInspectorViewProvider.js
  src/ui/components/List/ListView.vue
Labels: type:feature

#7422 Skip some tests, fix a mislabeled test, and add default condition for tabs
  e2e/tests/functional/plugins/conditionSet/conditionSet.e2e.spec.js
  e2e/tests/functional/plugins/gauge/gauge.e2e.spec.js
  e2e/tests/functional/plugins/plot/overlayPlot.e2e.spec.js
  e2e/tests/functional/plugins/plot/plotRendering.e2e.spec.js
  e2e/tests/functional/plugins/tabs/tabs.e2e.spec.js
  e2e/tests/performance/tabs.perf.spec.js
Labels: type:maintenance

#7199 Make Tabs eager loading configurable but default to false
  e2e/tests/functional/plugins/tabs/tabs.e2e.spec.js
  src/plugins/tabs/plugin.js
  src/plugins/tabs/pluginSpec.js
Labels: type:enhancement, notable_change

#7391 Support telemetry batching and move WebSocket handling to worker
  .cspell.json
  src/api/telemetry/BatchingWebSocket.js
  src/api/telemetry/TelemetryAPI.js
  src/api/telemetry/TelemetryAPISpec.js
  src/api/telemetry/TelemetryCollection.js
  src/api/telemetry/WebSocketWorker.js
  src/plugins/plot/configuration/Model.js
  src/plugins/plot/configuration/PlotSeries.js
  src/plugins/remoteClock/RemoteClock.js
Labels: type:feature, notable_change, pr:e2e:perf

#7415 Use different root for `renderWhenVisible`
  e2e/tests/functional/plugins/plot/overlayPlot.e2e.spec.js
  src/plugins/inspectorDataVisualization/NumericDataInspectorView.vue
  src/plugins/plot/chart/MctChart.vue
  src/ui/components/ObjectView.vue
  src/utils/visibility/VisibilityObserver.js
Labels: type:bug

#7315 Fix constrast for accessibility
  e2e/avpFixtures.js
  e2e/tests/functional/plugins/plot/autoscale.e2e.spec.js-snapshots/autoscale-canvas-panned-chrome-linux.png
  e2e/tests/functional/plugins/plot/autoscale.e2e.spec.js-snapshots/autoscale-canvas-prepan-chrome-linux.png
  e2e/tests/functional/plugins/styling/flexLayoutStyling.e2e.spec.js
  e2e/tests/functional/plugins/styling/stackedPlotStyling.e2e.spec.js
  e2e/tests/visual-a11y/a11y.visual.spec.js
  e2e/tests/visual-a11y/components/header.visual.spec.js
  e2e/tests/visual-a11y/components/inspector.visual.spec.js
  e2e/tests/visual-a11y/notebook.visual.spec.js
  e2e/tests/visual-a11y/planning.visual.spec.js
  src/plugins/folderView/components/grid-view.scss
  src/plugins/folderView/components/list-item.scss
  src/plugins/inspectorViews/properties/location.scss
  src/plugins/timeConductor/date-picker.scss
  src/styles/_constants-espresso.scss
  src/styles/_constants-maelstrom.scss
  src/styles/_constants-snow.scss
  src/styles/_controls.scss
  src/styles/_status.scss
  src/styles/notebook.scss
  src/ui/inspector/inspector.scss
  src/ui/layout/layout.scss
  src/ui/layout/pane.scss
  src/ui/layout/search/GrandSearch.vue
  src/ui/layout/search/SearchResultsDropDown.vue
  src/ui/layout/search/search.scss
  src/ui/toolbar/components/toolbar-checkbox.scss
Labels: type:enhancement

#7436 [e2e] Steps to reduce flakiness in test reporting
  .circleci/config.yml
  .github/workflows/e2e-flakefinder.yml
  e2e/tests/functional/tooltips.e2e.spec.js
Labels: type:maintenance

#7413 Add support for multiple CouchDB databases, multiple namespaces, and `readOnly` configurations
  .cspell.json
  src/api/objects/ObjectAPI.js
  src/plugins/CouchDBSearchFolder/pluginSpec.js
  src/plugins/localStorage/LocalStorageObjectProvider.js
  src/plugins/myItems/README.md
  src/plugins/myItems/myItemsInterceptor.js
  src/plugins/myItems/plugin.js
  src/plugins/persistence/couch/CouchChangesFeed.js
  src/plugins/persistence/couch/CouchObjectProvider.js
  src/plugins/persistence/couch/CouchSearchProvider.js
  src/plugins/persistence/couch/README.md
  src/plugins/persistence/couch/plugin.js
Labels: type:feature

#7378 Add Expanded view for Time List
  .cspell.json
  e2e/tests/functional/planning/timelist.e2e.spec.js
  src/plugins/plan/inspector/components/PlanActivitiesView.vue
  src/plugins/plan/inspector/components/PlanActivityStatusView.vue
  src/plugins/timelist/ExpandedViewItem.vue
  src/plugins/timelist/TimelistComponent.vue
  src/plugins/timelist/constants.js
  src/plugins/timelist/inspector/EventProperties.vue
  src/plugins/timelist/inspector/FilteringComponent.vue
  src/plugins/timelist/inspector/TimeListInspectorViewProvider.js
  src/plugins/timelist/inspector/TimelistPropertiesView.vue
  src/plugins/timelist/pluginSpec.js
  src/plugins/timelist/timelist.scss
  src/plugins/utcTimeSystem/UTCTimeFormat.js
  src/styles/_constants-espresso.scss
  src/styles/_constants-maelstrom.scss
  src/styles/_constants-snow.scss
Labels: type:feature
