Repository nasa/openmct, pull requests merged in 2024-06, with the labels that each got.

#7732 If display bounds are out of sync with time conductor, don't purge data out of bounds
  e2e/appActions.js
  e2e/tests/functional/plugins/plot/autoscale.e2e.spec.js
  e2e/tests/functional/plugins/plot/plotActions.js
  e2e/tests/functional/plugins/plot/plotControls.e2e.spec.js
  src/plugins/plot/MctPlot.vue
  src/plugins/timeConductor/TimePopupRealtime.vue
Labels: type:bug

#7731 Ensure time conductor mode is set when synchronizing time range
  e2e/tests/functional/plugins/plot/plotRendering.e2e.spec.js
  src/plugins/plot/MctPlot.vue
Labels: type:bug

#7699 fix(publishing): no index.html on npm pack
  .npmignore
Labels: type:maintenance, source:community, pr:e2e:couchdb, notable_change

#7753 [a11y] re-enable and fix all failing plan tests
  .circleci/config.yml
  e2e/tests/visual-a11y/planning-gantt.visual.spec.js
  e2e/tests/visual-a11y/planning-timelist.visual.spec.js
  e2e/tests/visual-a11y/planning-view.visual.spec.js
  package.json
  src/plugins/timelist/timelist.scss
  src/styles/_constants-espresso.scss
Labels: severity:critical, type:maintenance

#7756 Fix some flaky percy behavior
  e2e/.percy.ci.yml
  e2e/.percy.nightly.yml
  e2e/package.json
  e2e/playwright-visual-a11y.config.js
  e2e/tests/visual-a11y/displayLayout.visual.spec.js
  e2e/tests/visual-a11y/imagery.visual.spec.js
  package-lock.json
Labels: type:maintenance
