Repository nasa/openmct, pull requests merged in 2024-02, with the labels that each got.

#7452 Have countdowns in the Timelist use a `-` symbol
  e2e/tests/functional/planning/timelist.e2e.spec.js
  src/plugins/timelist/TimelistComponent.vue
Labels: type:bug

#7454 test(visual): add unclipped activity names visual tests + a11y fixes
  .cspell.json
  e2e/tests/visual-a11y/planning.visual.spec.js
  src/ui/layout/PaneContainer.vue
Labels: type:maintenance

#7418 feat: Mission Status for Situational Awareness
  .cspell.json
  example/exampleUser/ExampleUserProvider.js
  src/api/user/StatusAPI.js
  src/api/user/StatusUserProvider.js
  src/api/user/UserAPISpec.js
  src/plugins/operatorStatus/operatorStatus/OperatorStatus.vue
  src/plugins/userIndicator/components/MissionStatusPopup.vue
  src/plugins/userIndicator/components/UserIndicator.vue
  src/plugins/userIndicator/plugin.js
  src/plugins/userIndicator/pluginSpec.js
  src/plugins/userIndicator/user-indicator.scss
  src/styles/_controls.scss
  src/styles/_global.scss
  src/styles/vue-styles.scss
  src/ui/composables/event.js
  src/ui/composables/resize.js
Labels: type:feature

#7448 Filter values as a string not an object
  src/plugins/plan/util.js
  src/plugins/timelist/inspector/FilteringComponent.vue
Labels: type:bug

#7459 Ensure previews work for plots
  e2e/tests/functional/plugins/plot/previews.e2e.spec.js
  src/api/overlays/Overlay.js
  src/plugins/plot/chart/MctChart.vue
  src/plugins/plot/draw/DrawWebGL.js
  src/ui/components/ObjectFrame.vue
  src/ui/preview/PreviewAction.js
  src/utils/visibility/VisibilityObserver.js
Labels: type:bug

#7462 test(e2e): add e2e and visual tests for Mission Status (plus a11y)
  e2e/tests/functional/missionStatus.e2e.spec.js
  e2e/tests/visual-a11y/missionStatus.visual.spec.js
  example/exampleUser/ExampleUserProvider.js
  src/plugins/folderView/components/GridView.vue
  src/plugins/userIndicator/components/MissionStatusPopup.vue
  src/plugins/userIndicator/components/UserIndicator.vue
Labels: type:maintenance

#7481 Ensure stacked plots show cumulative legend
  e2e/tests/functional/plugins/plot/stackedPlot.e2e.spec.js
  src/plugins/plot/inspector/PlotOptionsBrowse.vue
  src/plugins/plot/inspector/forms/LegendForm.vue
  src/plugins/plot/legend/PlotLegend.vue
  src/plugins/plot/legend/PlotLegendItemCollapsed.vue
  src/plugins/plot/legend/PlotLegendItemExpanded.vue
  src/plugins/plot/stackedPlot/StackedPlotItem.vue
Labels: type:bug

#7478 Upgrade prettier and eslint compatibility libraries to latest
  .vscode/extensions.json
  package.json
  src/plugins/DeviceClassifier/src/DeviceMatchersSpec.js
Labels: type:maintenance

#7453 Plot legends expand by default when enabled
  .cspell.json
  e2e/tests/functional/plugins/plot/overlayPlot.e2e.spec.js
  e2e/tests/functional/plugins/plot/stackedPlot.e2e.spec.js
  src/plugins/persistence/couch/plugin.js
  src/plugins/plot/configuration/XAxisModel.js
  src/plugins/plot/inspector/PlotOptionsBrowse.vue
  src/plugins/plot/inspector/PlotOptionsItem.vue
  src/plugins/plot/inspector/forms/LegendForm.vue
  src/plugins/plot/inspector/forms/SeriesForm.vue
  src/plugins/plot/legend/PlotLegend.vue
  src/plugins/plot/legend/PlotLegendItemCollapsed.vue
  src/plugins/plot/legend/PlotLegendItemExpanded.vue
  src/plugins/plot/pluginSpec.js
  src/plugins/plot/stackedPlot/StackedPlotItem.vue
  src/plugins/plot/stackedPlot/pluginSpec.js
  src/styles/_legacy-plots.scss
Labels: type:bug

#7473 When plan view is used in a gantt chart, handle the domain object differently.
  src/plugins/plan/components/PlanView.vue
Labels: type:bug

#7224 Misc memory leak fixes
  src/plugins/LADTable/LADTableView.js
  src/plugins/condition/ConditionSetViewProvider.js
  src/plugins/displayLayout/plugin.js
  src/plugins/plot/MctPlot.vue
  src/plugins/plot/MctTicks.vue
  src/plugins/plot/axis/XAxis.vue
  src/plugins/plot/axis/YAxis.vue
  src/plugins/plot/inspector/PlotOptionsBrowse.vue
  src/plugins/plot/inspector/PlotOptionsEdit.vue
  src/plugins/plot/inspector/PlotOptionsItem.vue
  src/plugins/plot/inspector/forms/SeriesForm.vue
  src/plugins/plot/stackedPlot/mixins/objectStyles-mixin.js
  src/plugins/tabs/tabs.js
  src/plugins/telemetryTable/TelemetryTableView.js
  src/plugins/viewLargeAction/viewLargeAction.js
Labels: type:maintenance

#7503 Bypass cache/dirty when canceling transaction
  e2e/tests/functional/plugins/styling/flexLayoutStyling.e2e.spec.js
  src/api/objects/ObjectAPI.js
  src/api/objects/ObjectAPISpec.js
  src/api/objects/Transaction.js
  src/ui/toolbar/components/ToolbarColorPicker.vue
Labels: type:bug

#7504 Ensure object specific actions load in previews
  e2e/tests/functional/plugins/preview/preview.e2e.spec.js
  e2e/tests/functional/plugins/telemetryTable/preview.e2e.spec.js
  src/ui/preview/PreviewContainer.vue
Labels: type:bug

#7458 style: ensure legacy indicators align with Vue indicators
  src/utils/vueWrapHtmlElement.js
Labels: type:bug, bug:visual

#7506 chore: bump version to `4.0.0-next`
  package.json
Labels: type:maintenance

#7247 [CLA Approved] Add openmct type hints
  openmct.js
Labels: source:community, pr:e2e:couchdb, type:docs

#7509 Check role when receiving status updates in the Operator Status Indicator
  src/plugins/operatorStatus/operatorStatus/OperatorStatus.vue
Labels: type:bug

#7514 docs: Update release.yml and docs
  .github/PULL_REQUEST_TEMPLATE.md
  .github/release.yml
  docs/src/process/release.md
Labels: type:docs

#7517 docs(release.yml): make plural
  .github/release.yml
Labels: type:maintenance

#7518 docs: update release.yml
  .github/PULL_REQUEST_TEMPLATE.md
  .github/release.yml
  docs/src/process/release.md
Labels: type:maintenance

#7474 Remove all logic around auto centering and scrolling the timelist
  src/plugins/timelist/TimelistComponent.vue
Labels: type:bug, notable_change

#7479 Allow test data toggle to be clicked
  e2e/tests/functional/plugins/conditionSet/conditionSet.e2e.spec.js
  e2e/tests/functional/plugins/notebook/notebook.e2e.spec.js
  e2e/tests/functional/recentObjects.e2e.spec.js
  e2e/tests/functional/tree.e2e.spec.js
  src/plugins/condition/components/TestData.vue
Labels: type:maintenance

#7532 fix(#7380): update example imagery urls (moved after NASA wordpress m…
  example/imagery/plugin.js
Labels: type:bug

#7533 chore: bump version to `3.2.1`
  package.json
Labels: type:maintenance

#7037 Fix visible toolbar overflow
  e2e/tests/visual-a11y/displayLayout.visual.spec.js
  src/ui/layout/PaneContainer.vue
  src/ui/layout/pane.scss
Labels: type:bug
