Repository nasa/openmct, pull requests merged in 2024-07, with the labels that each got.

#7735 chore(cspell): grammar fixes
  .cspell.json
  API.md
  docs/src/process/cycle.md
  docs/src/process/version.md
  e2e/README.md
  e2e/playwright-ci.config.js
  e2e/playwright-mobile.config.js
  e2e/tests/framework/exampleTemplate.e2e.spec.js
  src/api/overlays/Dialog.js
  src/api/overlays/Overlay.js
  src/api/overlays/OverlayAPI.js
  src/api/overlays/ProgressDialog.js
  src/api/overlays/Selection.js
  src/api/overlays/components/OverlayComponent.vue
  src/api/telemetry/TelemetryAPI.js
  src/api/telemetry/TelemetryAPISpec.js
  src/api/user/StoragePersistence.js
  src/api/user/UserAPI.js
  src/plugins/licenses/plugin.js
  src/plugins/notebook/components/NotebookEmbed.vue
  src/plugins/notificationIndicator/components/NotificationsList.vue
  src/plugins/summaryWidget/src/ConditionEvaluator.js
  src/plugins/viewDatumAction/ViewDatumAction.js
Labels: type:maintenance, pr:e2e:couchdb

#7762 chore: bump playwright to version `1.45.0`
  .circleci/config.yml
  .github/workflows/e2e-couchdb.yml
  .github/workflows/e2e-flakefinder.yml
  .github/workflows/e2e-perf.yml
  .github/workflows/e2e-pr.yml
  e2e/package.json
  e2e/tests/visual-a11y/components/timeConductor.visual.spec.js-snapshots/time-conductor-fixed-time-chrome-linux.png
  package-lock.json
Labels: type:maintenance

#7776 test(visual): skip flaky visual test
  e2e/tests/visual-a11y/components/timeConductor.visual.spec.js
Labels: type:maintenance

#7768 fix(package.json): consistent props
  e2e/package.json
Labels: type:maintenance, source:community, pr:e2e:couchdb

#7770 Plots correctly use configuration set on the parent if they can't their own
  e2e/tests/functional/plugins/plot/autoscale.e2e.spec.js
  e2e/tests/functional/plugins/plot/overlayPlot.e2e.spec.js
  e2e/tests/functional/plugins/plot/plotActions.js
  e2e/tests/functional/plugins/plot/plotControls.e2e.spec.js
  e2e/tests/functional/plugins/plot/stackedPlot.e2e.spec.js
  src/plugins/charts/bar/inspector/SeriesOptions.vue
  src/plugins/plot/inspector/PlotOptionsBrowse.vue
  src/plugins/plot/inspector/PlotOptionsEdit.vue
  src/plugins/plot/inspector/PlotOptionsItem.vue
  src/plugins/plot/inspector/forms/SeriesForm.vue
  src/plugins/plot/inspector/forms/YAxisForm.vue
  src/plugins/plot/stackedPlot/StackedPlotItem.vue
  src/ui/inspector/InspectorTabs.vue
Labels: type:bug

#7784 chore: disable codeql scanning for `e2e/` folder
  .github/codeql/codeql-config.yml
Labels: type:maintenance

#7785 chore: bump playwright to `1.45.2`
  .circleci/config.yml
  .github/workflows/e2e-couchdb.yml
  .github/workflows/e2e-flakefinder.yml
  .github/workflows/e2e-perf.yml
  .github/workflows/e2e-pr.yml
  e2e/package.json
  package-lock.json
Labels: type:maintenance

#7744 fix(#6812): Align Plot and Plan X-Axes in Time Strips
  e2e/tests/visual-a11y/planning-timestrip.visual.spec.js
  src/plugins/inspectorDataVisualization/TelemetryFrame.vue
  src/plugins/plan/components/ActivityTimeline.vue
  src/plugins/plot/MctPlot.vue
  src/plugins/plot/MctTicks.vue
  src/plugins/plot/PlotView.vue
  src/plugins/plot/PlotViewProvider.js
  src/plugins/plot/axis/YAxis.vue
  src/plugins/plot/chart/MctChart.vue
  src/plugins/plot/overlayPlot/OverlayPlotViewProvider.js
  src/plugins/plot/overlayPlot/pluginSpec.js
  src/plugins/plot/stackedPlot/StackedPlot.vue
  src/plugins/plot/stackedPlot/StackedPlotItem.vue
  src/plugins/plot/stackedPlot/StackedPlotViewProvider.js
  src/plugins/plot/stackedPlot/mixins/objectStyles-mixin.js
  src/plugins/plot/stackedPlot/pluginSpec.js
  src/plugins/timeline/TimelineViewLayout.vue
  src/plugins/timeline/TimelineViewProvider.js
  src/ui/components/TimeSystemAxis.vue
  src/ui/composables/alignmentContext.js
Labels: type:bug

#7792 fix(#7791): tc form shouldn't submit bounds changes on dismiss
  e2e/appActions.js
  e2e/tests/framework/appActions.e2e.spec.js
  e2e/tests/framework/generateLocalStorageData.e2e.spec.js
  e2e/tests/functional/plugins/imagery/exampleImagery.e2e.spec.js
  e2e/tests/functional/plugins/plot/logPlot.e2e.spec.js
  e2e/tests/functional/plugins/telemetryTable/telemetryTable.e2e.spec.js
  e2e/tests/functional/plugins/timeConductor/timeConductor.e2e.spec.js
  e2e/tests/visual-a11y/imagery.visual.spec.js
  src/plugins/timeConductor/ConductorInputsFixed.vue
  src/plugins/timeConductor/TimePopupFixed.vue
Labels: type:bug
