Repository nasa/openmct, pull requests merged in 2024-05, with the labels that each got.

#7713 chore(webpack): destruct version from pkgJson
  .webpack/webpack.common.mjs
Labels: type:maintenance, source:community

#7716 chore: bump playwright to v1.44.0
  .circleci/config.yml
  .github/workflows/e2e-couchdb.yml
  .github/workflows/e2e-flakefinder.yml
  .github/workflows/e2e-perf.yml
  .github/workflows/e2e-pr.yml
  e2e/package.json
  package-lock.json
Labels: type:maintenance

#7715 this is 2024. `*` observers no more.
  e2e/tests/functional/plugins/conditionSet/conditionSet.e2e.spec.js
  src/plugins/condition/ConditionManager.js
  src/plugins/condition/components/ConditionCollection.vue
  src/plugins/condition/components/ConditionItem.vue
  src/plugins/condition/components/ConditionSet.vue
  src/plugins/condition/components/TestData.vue
Labels: type:bug

#7720 [Telemetry Tables] Make sure tables auto scroll correctly on first load
  e2e/appActions.js
  e2e/tests/functional/plugins/telemetryTable/telemetryTable.e2e.spec.js
  src/plugins/telemetryTable/components/TableComponent.vue
Labels: type:bug

#7709 chore: upgrade eventemitter to v5.0.2
  .webpack/webpack.coverage.mjs
  package-lock.json
  package.json
  src/MCT.js
  src/plugins/LADTable/components/LadRow.vue
  src/plugins/clearData/ClearDataAction.js
  src/plugins/condition/components/inspector/StylesView.vue
  src/plugins/displayLayout/actions/CopyToClipboardAction.js
  src/plugins/displayLayout/components/TelemetryView.vue
  src/plugins/duplicate/DuplicateAction.js
  src/plugins/exportAsJSONAction/ExportAsJSONAction.js
  src/plugins/formActions/CreateAction.js
  src/plugins/formActions/CreateActionSpec.js
  src/plugins/formActions/EditPropertiesAction.js
  src/plugins/formActions/plugin.js
  src/plugins/goToOriginalAction/goToOriginalAction.js
  src/plugins/imagery/actions/OpenImageInNewTabAction.js
  src/plugins/imagery/actions/SaveImageAsAction.js
  src/plugins/imagery/components/AnnotationsCanvas.vue
  src/plugins/imagery/components/ImageryTimeView.vue
  src/plugins/imagery/components/ImageryView.vue
  src/plugins/imagery/lib/eventHelpers.js
  src/plugins/imagery/pluginSpec.js
  src/plugins/importFromJSONAction/ImportFromJSONAction.js
  src/plugins/inspectorDataVisualization/TelemetryFrame.vue
  src/plugins/linkAction/LinkAction.js
  src/plugins/linkAction/pluginSpec.js
  src/plugins/move/MoveAction.js
  src/plugins/newFolderAction/newFolderAction.js
  src/plugins/notebook/actions/CopyToNotebookAction.js
  src/plugins/notebook/actions/ExportNotebookAsTextAction.js
  src/plugins/notebook/components/NotebookEmbed.vue
  src/plugins/openInNewTabAction/openInNewTabAction.js
  src/plugins/plot/chart/MctChart.vue
  src/plugins/plot/draw/Draw2D.js
  src/plugins/plot/draw/DrawWebGL.js
  src/plugins/plot/lib/eventHelpers.js
  src/plugins/reloadAction/ReloadAction.js
  src/plugins/remove/RemoveAction.js
  src/plugins/summaryWidget/src/eventHelpers.js
  src/plugins/tabs/components/TabsComponent.vue
  src/plugins/telemetryTable/TelemetryTableRow.js
  src/plugins/timer/actions/PauseTimerAction.js
  src/plugins/timer/actions/RestartTimerAction.js
  src/plugins/timer/actions/StartTimerAction.js
  src/plugins/timer/actions/StopTimerAction.js
  src/plugins/viewDatumAction/ViewDatumAction.js
  src/plugins/viewLargeAction/viewLargeAction.js
  src/ui/components/ObjectLabel.vue
  src/ui/layout/CreateButton.vue
  src/ui/layout/RecentObjectsListItem.vue
  src/ui/layout/search/AnnotationSearchResult.vue
  src/ui/layout/search/ObjectSearchResult.vue
  src/ui/preview/PreviewAction.js
  src/ui/preview/PreviewHeader.vue
  src/ui/preview/ViewHistoricalDataAction.js
Labels: type:maintenance, performance

#7736 fix(#7670): Ensure objects unsubscribe from staleness when destroyed
  e2e/tests/functional/staleness.e2e.spec.js
  example/generator/SinewaveStalenessProvider.js
  src/ui/components/ObjectView.vue
Labels: type:bug
