Repository nasa/openmct, pull requests merged in 2024-03, with the labels that each got.

#7492 [Mobile] Center Confirmation Dialog Texts
  e2e/playwright-mobile.config.js
  e2e/tests/mobile/smoke.e2e.spec.js
  src/api/overlays/components/OverlayComponent.vue
  src/api/overlays/components/dialog-component.scss
  src/api/overlays/components/overlay-component.scss
Labels: type:bug

#7151 Limit lines handle plot resizing
  e2e/tests/functional/plugins/plot/overlayPlot.e2e.spec.js
  src/plugins/plot/PlotView.vue
  src/plugins/plot/chart/MctChart.vue
  src/plugins/plot/inspector/forms/SeriesForm.vue
  src/plugins/plot/stackedPlot/StackedPlotItem.vue
Labels: type:bug

#7531 fix(overlay plot): legend updates correctly when removing element via remove action
  e2e/tests/functional/plugins/plot/overlayPlot.e2e.spec.js
  src/plugins/plot/legend/PlotLegend.vue
  src/plugins/plot/legend/PlotLegendItemCollapsed.vue
Labels: type:bug

#7548 [CI] Temp disable flakefinder as we it's generating too many GHA minutes
  .github/workflows/e2e-flakefinder.yml
Labels: type:maintenance

#7550 chore: minor formatting fix for PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: type:maintenance

#7485 d3 implementation of progress pie chart
  e2e/README.md
  e2e/helper/planningUtils.js
  e2e/tests/framework/generateLocalStorageData.e2e.spec.js
  e2e/tests/functional/planning/timelist.e2e.spec.js
  e2e/tests/functional/planning/timelistControlledClock.e2e.spec.js
  e2e/tests/functional/plugins/timer/timer.e2e.spec.js
  e2e/tests/visual-a11y/components/header.visual.spec.js
  e2e/tests/visual-a11y/components/inspector.visual.spec.js
  e2e/tests/visual-a11y/controlledClock.visual.spec.js
  e2e/tests/visual-a11y/faultManagement.visual.spec.js
  e2e/tests/visual-a11y/missionStatus.visual.spec.js
  e2e/tests/visual-a11y/planning.visual.spec.js
  package.json
  src/plugins/timelist/ExpandedViewItem.vue
  src/plugins/timelist/TimelistComponent.vue
  src/plugins/timelist/svg-progress.js
  src/plugins/timelist/timelist.scss
Labels: type:feature

#7559 fix(#7215)[Fault Management]: Fix shelving and acknowledging faults with single and bulk actions
  e2e/helper/faultUtils.js
  e2e/tests/functional/plugins/faultManagement/faultManagement.e2e.spec.js
  e2e/tests/visual-a11y/faultManagement.visual.spec.js
  example/faultManagement/exampleFaultSource.js
  example/faultManagement/utils.js
  src/plugins/faultManagement/FaultManagementListHeader.vue
  src/plugins/faultManagement/FaultManagementListItem.vue
  src/plugins/faultManagement/FaultManagementListView.vue
  src/plugins/faultManagement/FaultManagementToolbar.vue
  src/plugins/faultManagement/FaultManagementView.vue
Labels: type:bug

#7515 [Mobile] Make Time Conductor Usable Again
  e2e/tests/mobile/smoke.e2e.spec.js
  src/plugins/timeConductor/TimePopupFixed.vue
  src/plugins/timeConductor/TimePopupRealtime.vue
  src/plugins/timeConductor/conductor.scss
Labels: type:bug, type:maintenance

#7542 fix(#7524): Open in New Tab action from a sub-object in a layout
  .vscode/extensions.json
  e2e/appActions.js
  e2e/test-data/display_layout_with_child_overlay_plot.json
  e2e/tests/framework/appActions.e2e.spec.js
  e2e/tests/framework/generateLocalStorageData.e2e.spec.js
  e2e/tests/functional/planning/timestrip.e2e.spec.js
  e2e/tests/functional/plugins/conditionSet/conditionSet.e2e.spec.js
  e2e/tests/functional/plugins/displayLayout/displayLayout.e2e.spec.js
  e2e/tests/functional/plugins/flexibleLayout/flexibleLayout.e2e.spec.js
  e2e/tests/functional/plugins/gauge/gauge.e2e.spec.js
  e2e/tests/functional/plugins/inspectorDataVisualization/numericData.e2e.spec.js
  e2e/tests/functional/plugins/notebook/notebookSnapshots.e2e.spec.js
  e2e/tests/functional/plugins/styling/flexLayoutStyling.e2e.spec.js
  e2e/tests/functional/plugins/styling/styleInspectorOptions.e2e.spec.js
  e2e/tests/performance/contract/imagery.contract.perf.spec.js
  e2e/tests/visual-a11y/components/header.visual.spec.js
  e2e/tests/visual-a11y/styling.visual.spec.js
  e2e/tests/visual-a11y/telemetryViews.visual.spec.js
  example/dataVisualization/components/ExampleDataVisualizationSource.vue
  index.html
  src/api/menu/components/MenuComponent.vue
  src/api/menu/components/SuperMenu.vue
  src/plugins/LADTable/components/LadRow.vue
  src/plugins/clock/components/ClockIndicator.vue
  src/plugins/inspectorDataVisualization/NumericDataInspectorView.vue
  src/plugins/inspectorDataVisualization/TelemetryFrame.vue
  src/plugins/notebook/components/NotebookEmbed.vue
  src/plugins/notebook/components/NotebookMenuSwitcher.vue
  src/plugins/openInNewTabAction/openInNewTabAction.js
  src/plugins/timeConductor/independent/IndependentTimeConductor.vue
  src/styles/_global.scss
  src/tools/url.js
  src/tools/urlSpec.js
  src/ui/components/ObjectFrame.vue
  src/ui/layout/AppLayout.vue
  src/ui/layout/CreateButton.vue
  src/ui/layout/ViewSwitcher.vue
  src/ui/layout/search/ObjectSearchResult.vue
  src/ui/mixins/context-menu-gesture.js
  src/ui/mixins/object-link.js
Labels: type:bug, pr:e2e:couchdb

#7582 fix(#7015): Generate source maps for generating code coverage metrics
  .webpack/webpack.coverage.js
Labels: type:maintenance

#7529 [Telemetry Table] Address issues found during testing Table Performance
  e2e/appActions.js
  e2e/tests/functional/plugins/telemetryTable/telemetryTable.e2e.spec.js
  e2e/tests/visual-a11y/imagery.visual.spec.js
  src/plugins/telemetryTable/TelemetryTable.js
  src/plugins/telemetryTable/TelemetryTableType.js
  src/plugins/telemetryTable/components/TableComponent.vue
  src/plugins/telemetryTable/components/TableFooterIndicator.vue
  src/plugins/telemetryTable/components/TableRow.vue
  src/styles/_controls.scss
Labels: type:bug

#7567 allow inspector pane content to scroll vertically
  e2e/tests/functional/ui/inspector.e2e.spec.js
  e2e/tests/visual-a11y/imagery.visual.spec.js
  src/plugins/inspectorViews/properties/PropertiesComponent.vue
  src/ui/inspector/inspector.scss
  src/ui/layout/mct-tree.scss
  src/ui/layout/pane.scss
  src/ui/layout/search/search.scss
Labels: type:bug

#7555 fix(#7552): Fix notebook snapshot image annotations
  e2e/README.md
  e2e/tests/functional/plugins/flexibleLayout/flexibleLayout.e2e.spec.js
  e2e/tests/functional/plugins/notebook/notebookSnapshots.e2e.spec.js
  e2e/tests/visual-a11y/notebook.visual.spec.js
  src/api/overlays/components/OverlayComponent.vue
  src/plugins/notebook/components/NotebookEmbed.vue
  src/plugins/notebook/components/snapshot-template.html
  src/plugins/notebook/utils/painterroInstance.js
  src/plugins/timelist/TimelistComponent.vue
Labels: type:bug

#7565 Prevent Metadata Time System Error for Missing Objects
  e2e/tests/functional/plugins/plot/missingPlotObj.e2e.spec.js
  src/api/objects/ObjectAPI.js
  src/api/telemetry/TelemetryCollection.js
  src/plugins/plot/configuration/SeriesCollection.js
  src/plugins/plot/stackedPlot/StackedPlot.vue
  src/plugins/plot/stackedPlot/StackedPlotItem.vue
  src/ui/components/ObjectFrame.vue
  src/ui/layout/BrowseBar.vue
Labels: type:bug

#7493 [Plot] Fix plot swatch behavior when vertical space is small
  src/styles/_legacy-plots.scss
Labels: type:bug, needs:test instructions

#7597 Resize plans properly
  e2e/tests/visual-a11y/planning.visual.spec.js
  src/ui/components/TimeSystemAxis.vue
Labels: type:bug

#7596 [TC Popup] Fix Calendar so it is not cutoff
  e2e/tests/functional/plugins/timeConductor/datepicker.e2e.spec.js
  src/plugins/timeConductor/DatePicker.vue
  src/plugins/timeConductor/TimePopupFixed.vue
  src/plugins/timeConductor/conductor.scss
  src/styles/_mixins.scss
Labels: type:bug

#7613 For the setTimeConductorMode, use the close time popup button rather than the submit button to dismiss time popup
  e2e/appActions.js
  src/plugins/timeConductor/TimePopupFixed.vue
  src/plugins/timeConductor/TimePopupRealtime.vue
Labels: type:bug, bug:platform

#7601 [Telemetry Table] Telemetry mode bug fixes
  src/plugins/telemetryTable/TableConfigurationViewProvider.js
  src/plugins/telemetryTable/TelemetryTable.js
  src/plugins/telemetryTable/TelemetryTableConfiguration.js
  src/plugins/telemetryTable/TelemetryTableType.js
  src/plugins/telemetryTable/TelemetryTableView.js
  src/plugins/telemetryTable/components/TableComponent.vue
  src/plugins/telemetryTable/plugin.js
  src/plugins/telemetryTable/pluginSpec.js
Labels: type:bug

#7592 Ensure a request for telemetry happens in Condition Sets
  e2e/tests/functional/plugins/conditionSet/conditionSet.e2e.spec.js
  src/plugins/condition/ConditionManager.js
  src/plugins/condition/ConditionSetTelemetryProvider.js
  src/plugins/condition/pluginSpec.js
  src/plugins/notebook/pluginSpec.js
Labels: type:bug

#7619 Handle empty namespaces in import
  src/plugins/importFromJSONAction/ImportFromJSONAction.js
  src/plugins/importFromJSONAction/ImportFromJSONActionSpec.js
Labels: type:bug

#7618 [CI] Parallelize visual test runs
  .circleci/config.yml
Labels: type:maintenance

#7630 fix: 🤖 beep boop beep, you forgot an `await` 🤖
  e2e/tests/functional/plugins/conditionSet/conditionSet.e2e.spec.js
  src/plugins/condition/ConditionManager.js
Labels: type:bug

#7627 chore: bump `@playwright/test` to `1.42.1`
  .circleci/config.yml
  .github/workflows/e2e-couchdb.yml
  .github/workflows/e2e-flakefinder.yml
  .github/workflows/e2e-perf.yml
  .github/workflows/e2e-pr.yml
  package-lock.json
  package.json
Labels: type:maintenance

#7643 fix(#7633): add missing `await`
  e2e/tests/functional/plugins/lad/ladTable.e2e.spec.js
  src/plugins/LADTable/components/LadTable.vue
Labels: type:bug

#7632 For an existing View in a Preview, ensure we pull the same `ActionCollection`
  e2e/tests/functional/plugins/telemetryTable/preview.e2e.spec.js
  src/ui/preview/PreviewContainer.vue
  src/ui/preview/PreviewHeader.vue
Labels: type:bug

#7639 Disable reload in preview
  e2e/tests/functional/plugins/reloadAction/reloadAction.e2e.spec.js
  src/ui/preview/PreviewHeader.vue
Labels: type:bug

#7521 docs: Mission Status and more
  API.md
  e2e/avpFixtures.js
  e2e/baseFixtures.js
  e2e/helper/planningUtils.js
  e2e/helper/plotTagsUtils.js
  e2e/tests/functional/plugins/imagery/exampleImagery.e2e.spec.js
  openmct.js
  src/MCT.js
  src/api/Branding.js
  src/api/annotation/AnnotationAPI.js
  src/api/composition/CompositionCollection.js
  src/api/faultmanagement/FaultManagementAPI.js
  src/api/forms/FormsAPI.js
  src/api/menu/MenuAPI.js
  src/api/notifications/NotificationAPI.js
  src/api/objects/InMemorySearchProvider.js
  src/api/objects/ObjectAPI.js
  src/api/overlays/OverlayAPI.js
  src/api/telemetry/BatchingWebSocket.js
  src/api/telemetry/TelemetryAPI.js
  src/api/telemetry/WebSocketWorker.js
  src/api/time/TimeAPI.js
  src/api/time/TimeContext.js
  src/api/tooltips/ToolTipAPI.js
  src/api/user/StatusAPI.js
  src/api/user/User.js
  src/api/user/UserAPI.js
  src/api/user/UserProvider.js
  src/exporters/ImageExporter.js
  src/plugins/activityStates/activityStatesInterceptor.js
  src/plugins/autoflow/AutoflowTabularController.js
  src/plugins/displayLayout/LayoutDrag.js
  src/plugins/exportAsJSONAction/ExportAsJSONAction.js
  src/plugins/importFromJSONAction/ImportFromJSONAction.js
  src/plugins/persistence/couch/CouchDocument.js
  src/plugins/plan/plugin.js
  src/plugins/plan/util.js
  src/plugins/plot/configuration/Collection.js
  src/plugins/plot/configuration/Model.js
  src/plugins/plot/configuration/PlotSeries.js
  src/plugins/plot/configuration/YAxisModel.js
  src/plugins/plot/stackedPlot/StackedPlot.vue
  src/plugins/summaryWidget/src/ConditionEvaluator.js
  src/plugins/summaryWidget/src/ConditionManager.js
  src/plugins/summaryWidget/src/SummaryWidget.js
  src/plugins/summaryWidget/src/TestDataItem.js
  src/plugins/telemetryTable/collections/TableRowCollection.js
  src/plugins/userIndicator/README.md
  src/selection/Selection.js
  src/ui/components/ObjectPath.vue
  src/ui/registries/InspectorViewRegistry.js
  src/ui/registries/ToolbarRegistry.js
  src/ui/registries/ViewRegistry.js
  src/ui/router/ApplicationRouter.js
  tsconfig.json
Labels: type:maintenance, type:docs

#7624 fix(#7623): Resize ConductorAxis properly
  .eslintrc.cjs
  .gitignore
  e2e/README.md
  e2e/avpFixtures.js
  e2e/baseFixtures.js
  e2e/constants.js
  e2e/helper/notebookUtils.js
  e2e/playwright-visual-a11y.config.js
  e2e/pluginFixtures.js
  e2e/tests/framework/baseFixtures.e2e.spec.js
  e2e/tests/functional/plugins/imagery/exampleImagery.e2e.spec.js
  e2e/tests/functional/plugins/inspectorDataVisualization/numericData.e2e.spec.js
  e2e/tests/functional/plugins/notebook/notebook.e2e.spec.js
  e2e/tests/functional/plugins/plot/autoscale.e2e.spec.js-snapshots/autoscale-canvas-panned-chrome-darwin
  e2e/tests/functional/plugins/plot/autoscale.e2e.spec.js-snapshots/autoscale-canvas-panned-chrome-darwin.png
  e2e/tests/functional/plugins/plot/autoscale.e2e.spec.js-snapshots/autoscale-canvas-prepan-chrome-darwin
  e2e/tests/functional/plugins/plot/autoscale.e2e.spec.js-snapshots/autoscale-canvas-prepan-chrome-darwin.png
  e2e/tests/functional/plugins/timeConductor/timeConductor.e2e.spec.js
  e2e/tests/performance/memory/navigation.memory.perf.spec.js
  e2e/tests/visual-a11y/a11y.visual.spec.js
  e2e/tests/visual-a11y/components/about.visual.spec.js
  e2e/tests/visual-a11y/components/header.visual.spec.js
  e2e/tests/visual-a11y/components/inspector.visual.spec.js
  e2e/tests/visual-a11y/components/timeConductor.visual.spec.js
  e2e/tests/visual-a11y/components/timeConductor.visual.spec.js-snapshots/time-conductor-axis-resized-chrome-linux.png
  e2e/tests/visual-a11y/components/timeConductor.visual.spec.js-snapshots/time-conductor-fixed-time-chrome-linux.png
  e2e/tests/visual-a11y/components/timeConductor.visual.spec.js-snapshots/time-conductor-realtime-chrome-linux.png
  e2e/tests/visual-a11y/components/tree.visual.spec.js
  e2e/tests/visual-a11y/controlledClock.visual.spec.js
  e2e/tests/visual-a11y/defaultPlugins.visual.spec.js
  e2e/tests/visual-a11y/displayLayout.visual.spec.js
  e2e/tests/visual-a11y/faultManagement.visual.spec.js
  e2e/tests/visual-a11y/imagery.visual.spec.js
  e2e/tests/visual-a11y/ladTable.visual.spec.js
  e2e/tests/visual-a11y/notebook.visual.spec.js
  e2e/tests/visual-a11y/notification.visual.spec.js
  e2e/tests/visual-a11y/planning.visual.spec.js
  e2e/tests/visual-a11y/search.visual.spec.js
  e2e/tests/visual-a11y/telemetryViews.visual.spec.js
  karma.conf.cjs
  package-lock.json
  package.json
  src/plugins/DeviceClassifier/src/DeviceClassifierSpec.js
  src/plugins/URLIndicatorPlugin/URLIndicatorSpec.js
  src/plugins/charts/bar/pluginSpec.js
  src/plugins/charts/scatter/pluginSpec.js
  src/plugins/importFromJSONAction/ImportFromJSONActionSpec.js
  src/plugins/localStorage/pluginSpec.js
  src/plugins/summaryWidget/src/Rule.js
  src/plugins/summaryWidget/src/input/ColorPalette.js
  src/plugins/summaryWidget/src/input/IconPalette.js
  src/plugins/timeConductor/ConductorAxis.vue
  src/ui/components/List/ListItem.vue
  src/utils/testing.js
Labels: type:bug, severity:critical

#7590 chore: remove `type: module`, create `openmct-e2e` subpackage
  .npmignore
  .webpack/webpack.common.mjs
  .webpack/webpack.coverage.mjs
  .webpack/webpack.dev.mjs
  .webpack/webpack.prod.mjs
  TESTING.md
  e2e/README.md
  e2e/index.js
  e2e/package-lock.json
  e2e/package.json
  e2e/playwright-ci.config.js
  e2e/playwright-local.config.js
  e2e/playwright-mobile.config.js
  e2e/playwright-performance-dev.config.js
  e2e/playwright-performance-prod.config.js
  e2e/playwright-visual-a11y.config.js
  e2e/playwright-watch.config.js
  e2e/tests/functional/forms.e2e.spec.js
  e2e/tests/functional/planning/ganttChart.e2e.spec.js
  e2e/tests/performance/contract/imagery.contract.perf.spec.js
  e2e/tests/performance/contract/notebook.contract.perf.spec.js
  e2e/tests/visual-a11y/components/inspector.visual.spec.js
  e2e/tests/visual-a11y/controlledClock.visual.spec.js
  e2e/tests/visual-a11y/defaultPlugins.visual.spec.js
  karma.conf.cjs
  package-lock.json
  package.json
  packages/e2e/.npmignore
  src/plugins/notebook/utils/painterroInstance.js
  tsconfig.json
Labels: type:maintenance

#7645 Mct7636
  src/plugins/telemetryTable/TelemetryTable.js
Labels: type:bug, severity:critical

#7652 fix: move file to correct folder
  e2e/.npmignore
Labels: type:maintenance
