Repository nasa/openmct, pull requests merged in 2024-10, with the labels that each got.

#7849 feat(Fault Management): allow fault providers to define shelve durations
  .circleci/config.yml
  .github/workflows/e2e-couchdb.yml
  e2e/helper/faultUtils.js
  e2e/tests/functional/plugins/faultManagement/faultManagement.e2e.spec.js
  example/faultManagement/exampleFaultSource.js
  example/faultManagement/utils.js
  package-lock.json
  package.json
  src/api/faultmanagement/FaultManagementAPI.js
  src/plugins/faultManagement/FaultManagementListItem.vue
  src/plugins/faultManagement/FaultManagementView.vue
Labels: type:enhancement, notable_change

#7859 chore: bump `@playwright/test` to 1.47.2
  .circleci/config.yml
  .github/workflows/e2e-couchdb.yml
  .github/workflows/e2e-flakefinder.yml
  .github/workflows/e2e-perf.yml
  .github/workflows/e2e-pr.yml
  .github/workflows/release.yml
  e2e/package.json
  package-lock.json
Labels: type:maintenance

#7841 [Conditionals] Increase performance, switch to TelemetryCollections
  e2e/tests/functional/plugins/styling/conditionSetStyling.e2e.spec.js
  src/plugins/condition/ConditionManager.js
  src/plugins/condition/pluginSpec.js
  src/plugins/plot/stackedPlot/mixins/objectStyles-mixin.js
Labels: type:enhancement, performance

#7864 chore: it is 2024.
  e2e/tests/functional/plugins/performanceIndicator/performanceIndicator.e2e.spec.js
  e2e/tests/functional/plugins/reloadAction/reloadAction.e2e.spec.js
  e2e/tests/functional/staleness.e2e.spec.js
  e2e/tests/functional/userRoles.e2e.spec.js
  karma.conf.cjs
  package.json
  src/plugins/plan/inspector/components/PlanActivityPropertiesView.vue
  src/plugins/plan/inspector/components/PlanActivityStatusView.vue
  src/plugins/reloadAction/ReloadAction.js
  src/plugins/reloadAction/plugin.js
  src/ui/layout/AboutDialog.vue
Labels: type:maintenance

#7867 [CI] Fix flake with clocks and state generators
  .circleci/config.yml
  e2e/appActions.js
  e2e/tests/framework/appActions.e2e.spec.js
  e2e/tests/functional/plugins/styling/conditionSetStyling.e2e.spec.js
  e2e/tests/visual-a11y/displayLayout.visual.spec.js
Labels: type:maintenance, pr:e2e:couchdb

#7863 Fix table sorting in descending order
  src/plugins/telemetryTable/collections/TableRowCollection.js
Labels: type:bug

#7858 Fix complex displays not loading
  src/api/telemetry/TelemetryAPI.js
  src/api/telemetry/TelemetryAPISpec.js
  src/api/telemetry/TelemetryCollection.js
  src/plugins/plan/components/PlanView.vue
  src/plugins/remoteClock/RemoteClock.js
  src/plugins/remoteClock/requestInterceptor.js
  src/plugins/timeConductor/ConductorInputsRealtime.vue
  src/ui/components/progress-bar.scss
Labels: type:bug, bug:regression, performance, build9-rc11

#7866 test(visual): Stabilize compass per timestamp
  example/imagery/plugin.js
  src/utils/random.js
Labels: type:maintenance

#7875 [Telemetry Tables] Fix sort issues
  src/plugins/telemetryTable/TelemetryTable.js
  src/plugins/telemetryTable/TelemetryTableConfiguration.js
  src/plugins/telemetryTable/collections/TableRowCollection.js
Labels: type:bug

#7855 Add script to lock object sub-tree and fix object locking bugs
  package-lock.json
  package.json
  src/plugins/duplicate/DuplicateAction.js
  src/plugins/formActions/EditPropertiesAction.js
  src/plugins/inspectorViews/properties/PropertiesComponent.vue
  src/plugins/persistence/couch/scripts/lockObjects.mjs
  src/plugins/persistence/couch/setup-couchdb.sh
  src/ui/layout/BrowseBar.vue
Labels: type:enhancement, notable_change

#7882 Don't persist current tab when display is locked
  e2e/tests/functional/plugins/tabs/tabs.e2e.spec.js
  e2e/tests/performance/tabs.perf.spec.js
  src/plugins/tabs/components/TabsComponent.vue
  src/ui/layout/BrowseBar.vue
Labels: type:bug

#7890 fix(vipergc-574): Use selected shelve duration for fault management
  src/api/faultmanagement/FaultManagementAPI.js
  src/plugins/faultManagement/FaultManagementView.vue
  src/plugins/faultManagement/constants.js
Labels: type:bug

#7886 Bugfix/7873 time conductor input validation
  e2e/appActions.js
  e2e/tests/functional/plugins/telemetryTable/telemetryTable.e2e.spec.js
  e2e/tests/functional/plugins/timeConductor/timeConductor.e2e.spec.js
  src/plugins/timeConductor/TimePopupFixed.vue
Labels: type:bug, bug:regression

#7895 Fix gantt chart swimlane order
  src/plugins/plan/components/PlanView.vue
Labels: type:bug

#7898 fix(#7892): restore "now" (marcus bains) line to planning views
  e2e/helper/planningUtils.js
  e2e/tests/visual-a11y/planning-gantt.visual.spec.js
  e2e/tests/visual-a11y/planning-timestrip.visual.spec.js
  e2e/tests/visual-a11y/planning-view.visual.spec.js
  src/plugins/plan/components/PlanView.vue
  src/ui/components/TimeSystemAxis.vue
Labels: type:bug

#7897 fix(vipergc-660): identify axis keys upon adding object to composition
  src/plugins/charts/bar/BarGraphView.vue
Labels: type:bug

#7901 Bump references to support node22
  .circleci/config.yml
  package-lock.json
  package.json
Labels: type:maintenance, notable_change

#7906 Encode urls for css background images
  e2e/test-data/rick space roll.jpg
  e2e/tests/functional/plugins/imagery/exampleImagery.e2e.spec.js
  e2e/tests/functional/plugins/imagery/exampleImageryFile.e2e.spec.js
  src/plugins/condition/components/inspector/StyleEditor.vue
  src/plugins/displayLayout/components/ImageView.vue
  src/plugins/imagery/components/ImageThumbnail.vue
  src/plugins/imagery/components/ImageryView.vue
  src/ui/layout/AppLogo.vue
  src/utils/encoding.js
Labels: type:bug

#7907 chore: remove `release.yml`
  .github/workflows/release.yml
Labels: type:maintenance

#7913 chore: bump @playwright/test to v1.48.1
  .circleci/config.yml
  .github/workflows/e2e-couchdb.yml
  .github/workflows/e2e-flakefinder.yml
  .github/workflows/e2e-perf.yml
  e2e/package.json
  package-lock.json
Labels: type:maintenance
