Repository nasa/openmct, pull requests merged in 2024-04, with the labels that each got.

#7658 fix(e2e): specify `.nyc_output` path as custom config setting
  .webpack/webpack.coverage.mjs
  e2e/baseFixtures.js
  e2e/playwright-ci.config.js
  e2e/playwright-local.config.js
  e2e/playwright-mobile.config.js
  e2e/playwright-performance-dev.config.js
  e2e/playwright-performance-prod.config.js
  e2e/playwright-visual-a11y.config.js
  e2e/playwright-watch.config.js
Labels: type:maintenance

#7626 [Telemetry Tables] Don't mutate configuration if object is not able to be persisted
  src/plugins/telemetryTable/TelemetryTableConfiguration.js
Labels: type:bug, severity:critical

#7656 Do not add unused created attribute to metadata of couch documents on create
  src/plugins/persistence/couch/CouchObjectProvider.js
Labels: type:bug

#7628 Handle the case where the pasted data is not an image
  src/plugins/notebook/components/NotebookEntry.vue
Labels: type:bug

#7668 Revert "Handle the case where the pasted data is not an image"
  src/plugins/notebook/components/NotebookEntry.vue
Labels: type:bug

#7679 Handle paste events for images and text properly
  e2e/helper/hotkeys/clipboard.js
  e2e/helper/hotkeys/hotkeys.js
  e2e/helper/notebookUtils.js
  e2e/tests/functional/plugins/notebook/notebook.e2e.spec.js
  src/plugins/notebook/components/NotebookEntry.vue
Labels: type:bug

#7688 chore: remove all usage of deprecated Time API methods
  src/api/time/GlobalTimeContext.js
  src/api/time/IndependentTimeContext.js
  src/api/time/TimeAPI.js
  src/api/time/TimeAPISpec.js
  src/api/time/TimeContext.js
  src/plugins/LADTable/components/LadRow.vue
  src/plugins/URLTimeSettingsSynchronizer/URLTimeSettingsSynchronizer.js
  src/plugins/charts/bar/BarGraphView.vue
  src/plugins/charts/scatter/ScatterPlotView.vue
  src/plugins/condition/Condition.js
  src/plugins/condition/ConditionManager.js
  src/plugins/condition/StyleRuleManager.js
  src/plugins/condition/criterion/AllTelemetryCriterion.js
  src/plugins/displayLayout/components/TelemetryView.vue
  src/plugins/gauge/GaugePluginSpec.js
  src/plugins/gauge/components/GaugeComponent.vue
  src/plugins/imagery/components/ImageryTimeView.vue
  src/plugins/imagery/components/RelatedTelemetry/RelatedTelemetry.js
  src/plugins/imagery/mixins/imageryData.js
  src/plugins/notebook/components/NotebookComponent.vue
  src/plugins/notebook/components/NotebookEmbed.vue
  src/plugins/notebook/components/NotebookEntry.vue
  src/plugins/notebook/components/NotebookMenuSwitcher.vue
  src/plugins/notebook/utils/notebook-entries.js
  src/plugins/plan/components/PlanView.vue
  src/plugins/plan/inspector/components/PlanActivitiesView.vue
  src/plugins/plot/MctPlot.vue
  src/plugins/plot/chart/MctChart.vue
  src/plugins/plot/configuration/PlotSeries.js
  src/plugins/plot/configuration/XAxisModel.js
  src/plugins/remoteClock/RemoteClock.js
  src/plugins/summaryWidget/src/telemetry/SummaryWidgetEvaluator.js
  src/plugins/telemetryMean/src/MeanTelemetryProviderSpec.js
  src/plugins/telemetryMean/src/TelemetryAverager.js
  src/plugins/telemetryTable/TelemetryTable.js
  src/plugins/telemetryTable/components/TableComponent.vue
  src/plugins/timeConductor/ConductorPopUp.vue
  src/plugins/timeline/TimelineViewLayout.vue
  src/plugins/timelist/TimelistComponent.vue
  src/utils/staleness.js
Labels: type:maintenance, notable_change

#7654 Improve performance of JSON import and add progress bar
  src/plugins/importFromJSONAction/ImportFromJSONAction.js
  src/plugins/importFromJSONAction/ImportFromJSONActionSpec.js
Labels: type:enhancement, performance

#7695 refactor: remove the final `.bounds()` call
  src/api/time/IndependentTimeContext.js
Labels: type:maintenance

#7637 Fix nested Flexible Layout direction problem
  e2e/tests/functional/plugins/flexibleLayout/flexibleLayout.e2e.spec.js
  e2e/tests/functional/tooltips.e2e.spec.js
  src/plugins/flexibleLayout/components/ContainerComponent.vue
  src/plugins/flexibleLayout/components/FlexibleLayout.vue
  src/plugins/flexibleLayout/components/flexible-layout.scss
  src/plugins/flexibleLayout/toolbarProvider.js
Labels: type:bug, bug:regression
