Repository nasa/openmct, pull requests merged in 2024-09, with the labels that each got.

#7824 fix(conditional styling): conditional visibility for images and alpha-numerics in display layouts
  e2e/test-data/condition_set_storage.json
  e2e/tests/framework/generateLocalStorageData.e2e.spec.js
  e2e/tests/functional/plugins/styling/conditional/displayLayoutConditionalStyling.e2e.spec.js
  src/plugins/condition/components/ConditionCollection.vue
  src/plugins/displayLayout/components/ImageView.vue
  src/plugins/displayLayout/components/TelemetryView.vue
  src/ui/registries/ToolbarRegistry.js
  src/ui/toolbar/components/ToolbarButton.vue
  src/ui/toolbar/components/ToolbarMenu.vue
Labels: type:bug

#7832 chore: bump version to `4.1.0-next`
  e2e/package.json
  package.json
Labels: type:maintenance

#7843 [Build] Update package lock to reference correct version of package and also update the browserlist
  package-lock.json
Labels: type:maintenance

#7845 [Build] Update tsconfig to explicitly set `target` and `module` options
  tsconfig.json
Labels: type:maintenance

#7811 Bar graphs should only get latest historical datum
  src/plugins/charts/bar/BarGraphView.vue
Labels: type:bug

#7842 fix(#7825): imagery pause
  e2e/helper/imageryUtils.js
  e2e/tests/functional/plugins/imagery/exampleImagery.e2e.spec.js
  e2e/tests/functional/plugins/imagery/exampleImageryControlledClock.e2e.spec.js
  src/api/telemetry/TelemetryCollection.js
  src/plugins/imagery/components/ImageryTimeView.vue
  src/plugins/imagery/components/ImageryView.vue
  src/plugins/imagery/mixins/imageryData.js
  src/plugins/timeline/TimelineViewLayout.vue
Labels: type:bug

#7821 Fix bad color value for Gauge 'Needle' type
  e2e/.eslintrc.cjs
  e2e/README.md
  e2e/tests/visual-a11y/defaultPlugins.visual.spec.js
  e2e/tests/visual-a11y/gauge.visual.spec.js
  e2e/tests/visual-a11y/notebook.visual.spec.js
  e2e/tests/visual-a11y/search.visual.spec.js
  src/styles/_constants-espresso.scss
  src/styles/_constants-maelstrom.scss
  src/styles/_constants-snow.scss
Labels: type:bug, pr:e2e:couchdb

#7837 Improve telemetry buffering implementation
  e2e/tests/functional/plugins/performanceIndicator/performanceIndicator.e2e.spec.js
  src/api/telemetry/BatchingWebSocket.js
  src/api/telemetry/WebSocketWorker.js
  src/plugins/performanceIndicator/plugin.js
Labels: type:enhancement, notable_change
